### ISSUE TITLE
CRUD API argument order

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#10]
Hi,

I was looking through the docs, and am wondering if there is any specific reason to place `id` as second arg for `replace` and `update`. Not sure if there are others though.

May I suggest to make all consistent to place `id` as the first arg for operations that requires an `id`?

---

```js
// find(filters)
// findOne(filters)
// findById(id)
// remove(id)
// replace(id, data)
// update(id, data)
```

And I refer to this [primitive-key-value-operations](https://docs.couchbase.com/nodejs-sdk/current/concept-docs/documents.html#primitive-key-value-operations) where `id` is always in the first arg

**Comment by AV25242** [comment]
Good suggesion, will see that its consistent

**Comment by AV25242** [comment]
Issue has been created

**Comment by bwgjoseph** [comment]
Seem like all has been completed except [replace](https://github.com/couchbaselabs/node-ottoman/blob/484888fe1bf57a7754af5744bc527a5dc4d20dc2/src/model/model.ts#L162). Is there plan for that?

I guess following the convention, it would be `replaceById`?

While we are at it, what is the difference between using `replace` and `updateById`?

**Comment by AV25242** [comment]
@bwgjoseph  replace is what is used under the hood, I think you are mixing up our Nodejs SDK to Ottoman. The names Ottoman Choses are not exactly the same as the underlying SDK.  So there is no difference and update is provided by UpdateById

**Comment by bwgjoseph** [comment]
I don't think I mixed up the [API](https://github.com/couchbaselabs/node-ottoman/blob/484888fe1bf57a7754af5744bc527a5dc4d20dc2/src/model/model.ts#L162).

![image](https://user-images.githubusercontent.com/37484538/104048414-2351ec00-521e-11eb-8446-595477cd4a8e.png)

Signature is as such `replace(data: any, id?: string): Promise<any>`

---

So in `ottoman`, I can use both `replace` and `updateById` which is why I'm asking

- what is the difference?
- when do I use one over another?
- And if there is no difference, why is there a need to have 2 API that does exactly the same?

**Comment by AV25242** [comment]
@bwgjoseph, sorry for the confusion :) 

Replace - is an additional wrapper that will replace the entire document
Update on the other hand can accept a subset of document. Both uses nodejs sdk replace kv operation under the hood

**Comment by bwgjoseph** [comment]
Thank you.

In that case, the `replace` API will also be updated as mentioned?

`replace(id, data)`

**Comment by AV25242** [comment]
@bwgjoseph  replace currently is replacebyid (probably good to rename it) and document the differences between replace and update. Currently there is no (bulk operation) replaceMany - does UpdateMany suffice the needs?

**Comment by bwgjoseph** [comment]
As discussed, I don't have a specific use-case for `replaceMany` yet but that's just me. I'm not sure if the rest of the community using `ottoman` requires/expect such API to be available. Even without `replaceMany`, I could use `updateMany` as a replacement if I understand the API correctly.

**Comment by AV25242** [comment]
Documentation will be updated with example - https://github.com/couchbaselabs/node-ottoman/issues/353
