### ISSUE TITLE
ManyResponse interface declaration

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#100]
I mean the interface

```js
// should be
export interface ManyResponse {
    // note, no ?
    data: any[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}

// instead of
export interface ManyResponse {
    data?: any[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}
```

Since that, all multi-methods will always return `data`, it doesn't make sense to make it optional unless there is case where `data` is not being returned

_Originally posted by @bwgjoseph in https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/82#issuecomment-856892249_

**Comment by AV25242** [comment]
@bwgjoseph what I have been told is that data will always be returned even if its an empty array

**Comment by bwgjoseph** [comment]
Yup, that's correct. 

The issue here is that the interface is declared that the data **might** not be returned (optional as it was declared with ?)

As mentioned in the first post, the correct interface declaration should be

```js
export interface ManyResponse {
    // notice that there is no ? (question mark) after data
    data: T[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}
```

Below is the current declaration (with ? after data)

https://github.com/couchbaselabs/node-ottoman/blob/89520f200100600bc20ce08670a3cd8c8c4cc05a/src/handler/types.ts#L54-L59

**Comment by AV25242** [comment]
Ah ok, let me open a ticket to address this and see what is the response

**Comment by AV25242** [comment]
[v2.0.0-beta.3 released]( https://www.npmjs.com/package/ottoman/v/2.0.0-beta.3)
