### ISSUE TITLE
schema validation and error message

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#101]
Hi,

Just upgraded to `beta.2` and ran test, and notice some of the previous test fails. I'm not sure if it happens before `beta.1/2`.

Basically, I have schema where it has `enum` but it isn't a required field. When I ran the test, it is expecting me to provide those values.

Something along this line

```js
const airplaneSchema = {
    callsign: {
        type: String,
        required: true,
    },
    size: {
        type: String,
        enum: [
            'S',
            'M',
            'L',
        ],
    },
    type: {
        type: String,
        enum: [
            'ECONOMY',
            'FIRST CLASS',
            'PRIVATE',
        ],
        uppercase: true,
        trim: true,
    },
}
```

So this is the test case

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/3a4917a60ff99482631a2742bd497be2a5f5b388/test/ts/errorMsg.test.ts#L31-L53

2 issue

1. It's not a required field, so the validation should not be triggered
2. Even if it is triggered, the error message is not consistent

```js
"message": "Property 'name' is required, Property 'capacity' is more than the maximum allowed value of '550', Property 'model' is required, Property size value must be S,M,L, Property type value must be ECONOMY,FIRST CLASS,PRIVATE"
```

It is similar to the previous issue #72, so you see that `Property size value must be S,M,L`, where the `size` is not quoted like the rest

Thanks

**Comment by AV25242** [comment]
Will get back to you on this

**Comment by AV25242** [comment]
@bwgjoseph  this should be fixed with next release

**Comment by AV25242** [comment]
[v2.0.0-beta.3 released]( https://www.npmjs.com/package/ottoman/v/2.0.0-beta.3)
