### ISSUE TITLE
QueryScanConsistency not available

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#107]
Hi,

While trying the latest `beta.8`, and using the latest `couchbase:enterprise-7.0.0` docker image.

I am seeing this error

```js
Argument of type '{ consistency: string; }' is not assignable to parameter of type 'QueryOptions'.
  Object literal may only specify known properties, and 'consistency' does not exist in type 'QueryOptions'.      

         const queryFind = await getDefaultInstance().cluster.query(query, { consistency: 'request_plus' });
```

Which I believe is because of the recent change that it changes to `enum`

So I tried to make the change to 

```js
await getDefaultInstance().cluster.query(query, { scanConsistency: QueryScanConsistency.RequestPlus });
```

But `QueryScanConsistency` is not re-exported from `ottoman` and does not seem to be exported from `couchbase` too

![image](https://user-images.githubusercontent.com/37484538/130362946-97953783-68f6-4cb1-9f58-0b918deab58b.png)

It should be re-exported from `ottoman`, I believe

Thanks

**Comment by AV25242** [comment]
Could be strictly beta issue. I will reach out to the team and confirm.

**Comment by bwgjoseph** [comment]
Sure, thank you!

**Comment by AV25242** [comment]
We released [Ottoman beta.9](https://www.npmjs.com/package/ottoman/v/2.0.0-beta.9) today please verify
