### ISSUE TITLE
upsert operation

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#11]
Does `ottoman` don't support `upsert` KVO as defined in [here](https://docs.couchbase.com/nodejs-sdk/current/concept-docs/documents.html#primitive-key-value-operations)?

**Comment by AV25242** [comment]
No it doesn't

**Comment by bwgjoseph** [comment]
Any particular reason since it's part of the kv operations?

**Comment by AV25242** [comment]
Not that I can think of or have heard, I will check with the team. I know its a handy way to get a document created if it doesnt exist but there are alternatives built in Ottoman to go about it at present

**Comment by bwgjoseph** [comment]
I have an existing service that takes in a stream of incoming data, example location updates for device. 

As it comes from external source, it only perform `POST` request to my server, and I am currently using `upsert` to create or update the data. Without using `upsert`, I have to manually perform a get based on the filters, then determine whether to create/update the data. Hence, with `upsert`, it is much easier to work with.

And since it's part of the KV operations, I thought `ottoman` would have it as well. 

Don't mind letting me what is the implication of using the `upsert`? When would the exception occur, give my use-case?

Thanks!

**Comment by bwgjoseph** [comment]
Hi,

Can I clarify if the `findOneAndUpdate()` you proposed is meant for `upsert`?

If yes, then based on your example,

the operation (update) will happen if there's an existing doc. But won't create if there is no match.

You have to pass extra params if you want `update or create (upsert)`

```js
let doc = await Character.findOneAndUpdate(filter, update, {
  new: true,
  upsert: true // Make this update into an upsert
});
```

**Comment by bwgjoseph** [comment]
Verified working based on current test
