### ISSUE TITLE
registerGlobalPlugin api

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#113]
Hi,

While testing for `registerGlobalPlugin` api, I couldn't get it to run. I remember this test was running fine previously.

See https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/registerGlobalPlugin.test.ts

I kept getting this error, and no matter how many times I run it, it's still the same

![image](https://user-images.githubusercontent.com/37484538/134815486-51d6281a-efce-41b3-8dc4-63086817310f.png)

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

try to update the plugins to return the modified document:
const pluginLog = (pSchema: any) => {
    pSchema.pre('save', function (doc: any) {
        doc.operational = false;
        return doc;
    });
};

const pluginLog2 = (pSchema: any) => {
    pSchema.pre('save', function (doc: any) {
        doc.plugin = 'registered from plugin 2!'
        return doc;
    });
};

**Comment by bwgjoseph** [comment]
Hi,

I've tried but still not working

**Comment by bwgjoseph** [comment]
@gsi-alejandro 

In case you missed this, it's not working

**Comment by AV25242** [comment]
Hi @bwgjoseph  I spoke to @gsi-alejandro  he said there was no issue but he is going to look at your code repo and see what is missing. @gsi-alejandro  any updates ?

**Comment by gsi-alejandro** [comment]
I deep into your code and change the initOttoman to:

```
const initOttoman = async (consistency: SearchConsistency = SearchConsistency.NONE) => {
    ottoman = new Ottoman({ consistency });

    await ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'travel-sample',
        username: 'Administrator',
        password: 'password'
    });

    model('myschema', schema, { idKey: '_id' });

    await ottoman.start();
}
```

And it works

The change was register the `model` before execute the `start` function.


![image](https://user-images.githubusercontent.com/15661442/135494561-0dfe4384-8f61-4db9-938f-28c58e28446c.png)

**Comment by bwgjoseph** [comment]
Thanks @gsi-alejandro for spotting the mistake.

I made the changes, and had to run 4 times before I can finally get it running.
