### ISSUE TITLE
id type restricted to string?

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#12]
Based on the [model-defintion](https://github.com/couchbaselabs/node-ottoman/blob/master/src/model/model.ts), it seem like all `id` must be of type string but in the [node-sdk-docs](https://docs.couchbase.com/nodejs-sdk/current/concept-docs/documents.html#document), it defined 

> Document IDs (keys) are assigned by application. A valid document ID must:
> 
> Conform to UTF-8 encoding
> Be no longer than 250 bytes
> 
> You are free to choose any ID (key) for your document, so long as it conforms to the above restrictions. Unlike some other database, Couchbase does not automatically generate IDs for you, though you may use a separate counter to increment a serial number — you can also use UUIDs as keys, the best choice being determined by your use case.

So, any type should be acceptable? `string | number`?

**Comment by AV25242** [comment]
Probably this [documentation](https://docs.couchbase.com/server/current/learn/data/data.html) on the server side will give you a better idea.

Summary - Id is a string.

**Comment by bwgjoseph** [comment]
Thanks, I'll read up on this

**Comment by AV25242** [comment]
Thanks
