### ISSUE TITLE
$in, $nin operator

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#13]
Hi,

Is `$in` and `$nin` operator supported?

I saw in the previous issue https://github.com/couchbaselabs/node-ottoman/issues/150, and [forum](https://forums.couchbase.com/t/ottoman-find-where-value-is-in-array/10979) but don't see in [n1ql-where-clause-structure](https://v2.ottomanjs.com/guides/query-builder.html#n1ql-where-clause-structure).

**Comment by AV25242** [comment]
@question has been posted,  waiting on response.

**Comment by AV25242** [comment]
Yes, both functionalities exist fo the query builder.

{$in: {....}}
$not: {$in: {....}}

Ottoman v2 provides a very powerful query builder, please check this link for more information https://v2.ottomanjs.com/guides/query-builder.html

Notice: $nin operator doesn't exists but can be achieve by combining $not and $in operators $not: {$in: {....}}).

**Comment by bwgjoseph** [comment]
Thanks, will be trying it out.

In that case, the docs should be updated to include the `$in` operator since it's missing in the available operators list.

**Comment by AV25242** [comment]
> Thanks, will be trying it out.
> 
> In that case, the docs should be updated to include the `$in` operator since it's missing in the available operators list.

That is correct and already communicate. Docs will be updated.
