### ISSUE TITLE
save is not triggering updates

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#14]
Hi,

Based on the [save-docs](https://v2.ottomanjs.com/classes/model.html#save), it states that `save()` triggers a `save or update` of the document. But it doesn't seem like the case from the test case.

You can look at `save.test.ts`

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/3ae99d40ffab339245f01db08045715f4a692096/test/ts/save.test.ts#L63-L79

This is my output

```js
2 _Model {
  callsign: 'Hi',
  country: 'United State',
  name: 'Couchbase Airlines',
  id: '18c1dbf9-5c9d-41ec-8398-15421a6e0ee3',
  _type: 'Airline',
  _scope: '_default'
}
3 {
  meta: {
    requestId: 'fa80cd7d-8b8f-453b-9a86-e42c3705b567',
    clientContextId: '925cb2b8147a9762',
    status: 'success',
    signature: { '*': '*', _type: 'json' },
    profile: undefined,
    metrics: {
      elapsedTime: 6.69,
      executionTime: 6.6436,
      sortCount: undefined,
      resultCount: 2,
      resultSize: 311,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: [
    _Model {
      _scope: '_default',
      _type: 'Airline',
      callsign: 'Couchbase',
      country: 'United State',
      id: '1423be38-848b-4797-b680-f4afe1635d37',
      name: 'Couchbase Airlines'
    },
    _Model {
      _scope: '_default',
      _type: 'Airline',
      callsign: 'Hi',
      country: 'United State',
      id: '18c1dbf9-5c9d-41ec-8398-15421a6e0ee3',
      name: 'Couchbase Airlines'
    }
  ]
}
``` 

There are 2 docs instead of 1 document. Based on the documentation, I would expect only 1 rows returned and `callsign` to be the one with `Hi` but it seem to be creating another document.

Am I doing it wrong?

**Comment by AV25242** [comment]
@bwgjoseph  yeah 

 it('ottoman - should save doc', async () => { 
     const airlineSchema = new Schema(schema); 
     const Airline = model('Airline', airlineSchema); 
     const cbAirlines = new Airline(doc); 
     const created = await Airline.create(cbAirlines); 
     const options = { consistency: SearchConsistency.LOCAL } 
  
  
     **created.callsign** = "Hi"; 
     **await created.save();** 
     console.log(2,cbAirlines); 


You should try it from your object created not the original object.

**Comment by bwgjoseph** [comment]
Ah yes! Thanks for the correction, have verified it.
