### ISSUE TITLE
API to updateMany docs

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#15]
Similar to https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/5, it would be great to have a similar API to perform `updateMany`

`updateMany(filter, data)` will have any docs that matches the filter to be updated with the data defined

**Comment by AV25242** [comment]
Understood, the challenge is to refdocIndex and its management. Will discuss with team and get back.

**Comment by AV25242** [comment]
@bwgjoseph  do you have any use case around refdocIndexes, we are currently debating  removing it (mostly) as they add overhead of managing Indexes from the framework, or may be keep it with all caution documentation around it.

**Comment by bwgjoseph** [comment]
To be honest, I'm still don't quite understand fully with regards to all the indexing types and differences between those even though I read through some of the docs/articles. So I'm not sure if I can provide any good feedback at the moment.

---

So this is slightly unrelated but my confusion should be coming from my understanding of Couchbase as well, which I only recently began to learn.

I know there's 3 type of [indexes](https://v2.ottomanjs.com/guides/schema.html#index-types) I can define in `ottoman` - `refdoc, view and n1q1` but without example in the docs, it's quite difficult to relate to what those mean exactly. 

I was looking at [this](https://blog.couchbase.com/firstapp-couchbase-nodejs-ottoman/), and one of the example given was

```js
index: {	
        findByCustomerID:{				// ← refdoc index
            by:'customerID',
            type:'refdoc'
        },
        findByEmail: {					// ← refdoc index
            by: 'email',
            type: 'refdoc'
        },
        findByFirstName: {				// ← secondary index
            by: 'name.first'
        },
        findByLastName: {				// ← secondary index
            by: 'name.last'
        }
    }
```

which I think is great, but I still don't quite get the difference between them even though it has some kind of explanation there. As this article is pretty old, some of the stuff might be outdated/inaccurate/not longer valid.

So I was wondering if there's any updated docs/blog/video that explains `refdoc, view and n1q1` differences, with code example? And how is it linked to [Index Service](https://docs.couchbase.com/server/current/learn/services-and-indexes/services/index-service.html), [Query Service](https://docs.couchbase.com/server/current/learn/services-and-indexes/services/query-service.html), [GSI](https://docs.couchbase.com/server/current/learn/services-and-indexes/indexes/global-secondary-indexes.html) and so on. If there's any videos from the recent `couchbase.connect` would be excellent

Thanks!

**Comment by AV25242** [comment]
There are many Blogs (I am listing a few below), on View and GSI Indexes (N1QL), refdoc Index was migrated over from Ottoman V1 and is NOT a feature of Couchbase. We will most like deprecate it in future versions. We can discuss about it in our next meeting. 

https://blog.couchbase.com/couchbase-views-and-better-alternatives-part-1-of-2/
https://blog.couchbase.com/faster-indexing-and-query-with-memory-optimized-global-secondary-indexes-gsi/
https://blog.couchbase.com/couchbase-gsi-index-partitioning/

In addition our docs should give you a good picture.

In nutshell, there are 2 indexes Primary and Secondary (GSI or N1QL however you want to call it)  and the third one is View but has its own advantages and challenges if you may.

**Comment by bwgjoseph** [comment]
I see! I think that's partly where my confusion comes from. I was trying to find `refdoc` reference in couchbase docs but wasn't able to. Now that you mentioned it, my focus when reading the docs will be slightly different.

And with that, I also have a better grasp of your question posted to me. 

To answer that, I don't think I have any use case specifically for `refdoc` index, seeing that Secondary index should cover it (based on my current understanding of the indexes)

**Comment by bwgjoseph** [comment]
Hi,

I just tested, and found something interesting..

Take a look at this test case

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/851bcb736c94063cadcf9412754a731e07efe926/test/ts/updateMany.test.ts#L108

When I try to update `operational` field which is a `boolean` to a `string`, it did not fail, but the data did not change as well

```js
GenericManyQueryResponse {
  status: 'SUCCESS',
  message: { modified: 2, match_number: 2, errors: [] }
}

{
  meta: {
    requestId: 'db2232b9-6294-49e2-bb1b-17a33d2c80d9',
    clientContextId: '10db2864f4f460bb',
    status: 'success',
    signature: { '*': '*' },
    profile: undefined,
    metrics: {
      elapsedTime: 1.8356,
      executionTime: 1.768,
      sortCount: undefined,
      resultCount: 2,
      resultSize: 817,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: [
    _Model {
      _type: 'Airplane',
      callsign: 'Eagle',
      capacity: 500,
      destination: [Array],
      extension: 123,
      id: '0525d5d4-f602-43c0-8bd1-025354da299f',
      info: [Object],
      location: [Object],
      model: '767-300F',
      name: 'Couchbase Airlines',
      operational: true,
      scheduledAt: 2020-12-19T16:30:00.000Z,
      size: 'L'
    },
    _Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      capacity: 250,
      destination: [Array],
      extension: 'abc',
      id: '3bf50660-3012-4aa4-8932-5cc6ff0fc969',
      info: [Object],
      location: [Object],
      model: 'A380',
      name: 'Couchbase Airlines',
      operational: true,
      scheduledAt: 2020-11-20T03:30:00.000Z,
      size: 'S'
    }
  ]
}
```

But when I test by setting a `string` field to a boolean like `mode: false`, it will detect the error

**Comment by AV25242** [comment]
@bwgjoseph although it looks interesting, but do you think it would have to do something with strict option ? Is the strict false in this case ?

**Comment by bwgjoseph** [comment]
`strict` is not set to `false` in this case, so it should be `true`

**Comment by bwgjoseph** [comment]
@AV25242 in case you missed this

**Comment by AV25242** [comment]
Oh yeah, looking at bigger problems this one slipped. thanks will get back to you.

**Comment by gsi-chao** [comment]
@bwgjoseph we raise a PR to fix this problem

**Comment by AV25242** [comment]
@bwgjoseph please check to see if alpha.16 has solved this

**Comment by bwgjoseph** [comment]
This issue still exist, same issue as mentioned in https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/15#issuecomment-762395352

**Comment by gsi-chao** [comment]
@bwgjoseph, We found and fix a bug in the boolean casts, I hope it will be available soon.
We also add these cast options to booleans.
## Ottoman cast the following values to true
- true
- 'true'
- 1
- '1'
- 'yes'

## Ottoman cast the following values to false:
- false
- 'false'
- 0
- '0'
- 'no'

**Comment by AV25242** [comment]
@bwgjoseph  alpha16.2 was released today you should see the changes in

**Comment by bwgjoseph** [comment]
This seem better but still have issue w.r.t return type of batch operation (createMany, updateMany, removeMany). See #40

**Comment by AV25242** [comment]
@bwgjoseph  digging this issue back, I looked at #40 and you seem to be pretty convinced (let me know otherwise) and had questions around lean. Does this ticket still warrant to be opened ?

**Comment by bwgjoseph** [comment]
I mean I understand how it works but still not sure why it choose to return class instance than a JSON object by default. (See my latest reply over in #40). If that's how it works, and how it is being returned, then I will work with that. Since I don't have any valid use-case against it other than trying to figuring out more.

I will be verifying one last time, and then will close this together with #5 and #34.
