### ISSUE TITLE
define Model type

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#17]
In `mongoose`, I am able to declare the Model type by doing so

```js
interface AirlineInterface {
    callsign: string;
    country: string;
    name: string;
}

type MongooseAirlineModel = AirlineInterface & mongoose.Document;

const model = mongoose.model<MongooseAirlineModel>('Airline', mongooseAirlineSchema);
```

As such, it provides intellisense like

![image](https://user-images.githubusercontent.com/37484538/99559878-360b2a00-2a00-11eb-8469-7d923fd59c34.png)

![image](https://user-images.githubusercontent.com/37484538/99559939-47543680-2a00-11eb-80af-da4704cd1435.png)

Note that it knows how to infer the fields from my interface.

---

Does `ottoman` has something like this for me to declare as well?

**Comment by AV25242** [comment]
This is not currently supported

**Comment by bwgjoseph** [comment]
Would love to have this supported. This is pretty important for `typescript` users as the current definition seem to not taking advantage of the typings, hence, not allowing to providing intellisense in IDE. (I may be using it wrong, if so, please correct me)

For example, you don't even get the basic CRUD, etc intellisense

![image](https://user-images.githubusercontent.com/37484538/100757256-1bd24280-3429-11eb-9f82-5f30f39d7d49.png)

Even though in in [model.ts](https://github.com/couchbaselabs/node-ottoman/blob/master/src/model/model.ts) declaration, there's `Model` class but I'm not sure if it's being used (or if I can use it)

**Comment by AV25242** [comment]
Issue https://github.com/couchbaselabs/node-ottoman/issues/324 has been created

**Comment by bwgjoseph** [comment]
To build on to what we discussed earlier... 

Though I'm not sure if I am right or maybe there's some reason to use less strict types, but this is what I thought it should (somewhat) be..

```js
export abstract class Model<T = any> extends Document<T> {
	constructor(data: T) {
		super();
	}
	
	static async find(filter: LogicalWhereExpr = {}, options: FindOptions = {}): Promise<T> {
		return Promise.resolve({});
	}
	
	static async findById(id: string, options: FindByIdOptions = {}): Promise<T> {
		return Promise.resolve({});
	}
	
	static async create(data: T): Promise<T> {
		return Promise.resolve({});
	}
	
	// and so on
}
```

Also, not sure if it's already done but as a further enhancement, could use [keyof](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types) to infer the property of the interface so it could make the `filter` typing better.

**Comment by bwgjoseph** [comment]
Have verified that the basic intellisense are working for the model

![image](https://user-images.githubusercontent.com/37484538/102758251-723dfb80-43ad-11eb-9ece-14e52066ae0a.png)

Will close this first, but hoping the more advance one will come in future
