### ISSUE TITLE
suggestion: indicate SearchConsistency is defaulted to NONE if not provided

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#18]
As mentioned in the title, and reference to #8, I don't think I see anywhere in the v2 docs that NONE is the default. If I didn't missed it out, I think it would be great to add in somewhere in the docs.

Thanks

**Comment by AV25242** [comment]
Thanks  added this to the existing docs issues
https://github.com/couchbaselabs/node-ottoman/issues/311

**Comment by bwgjoseph** [comment]
This PR https://github.com/couchbaselabs/node-ottoman/pull/316 is closed but not merged? Is it a mistake?

**Comment by bwgjoseph** [comment]
Verified
