### ISSUE TITLE
schema options

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#19]
Hi,

We used quite a few of the built-in [schema options](https://mongoosejs.com/docs/schematypes.html#schematype-options) from `mongoose` and was wondering if `ottoman` does provide as well, and if not, what are the workaround/alternative?

Some of those that I can think off the top of my head are:

Types: `required, validate, immutable`  
Indexes: `unique, index`
Most (if not all) of `String, Number and Date`

> Depending on the discussion, we may want to spawn different issue for each of those options

So one of the first example we tried to test was `enum-uppercase.test.ts`, where we used `enum and uppercase` but it seem like `ottoman` doesn't support `uppercase`

It throws the following error when we tried to save using small capital `a`

```js
Error: Property direction value must be A,B,C
      at Schema.cast (node_modules\ottoman\src\schema\schema.ts:115:13)
      at Object.exports.castSchema (node_modules\ottoman\src\schema\helpers\fn-schema.ts:136:18)
      at Z:\Development\workspace\github\bwgjoseph\mongoose-vs-ottoman\node_modules\ottoman\src\model\utils\store-life-cycle.ts:16:14
      at Generator.next (<anonymous>)
      at fulfilled (node_modules\ottoman\lib\model\utils\store-life-cycle.js:5:58)
```

Thanks!

**Comment by AV25242** [comment]
@bwgjoseph  good questions

Some of them are internally supported by Ottoman as such like 
Required, validate
Types like string, number and date 

For special cases is where we have hooks, in this specific case you might want to use [pre validate hook](https://v2.ottomanjs.com/guides/schema.html#hooks) . Write your own transformation function that will convert to uppercase and call it in the hook.

Now on the unique there is nothing thats supported on the backend, however there are a few  ways you can address these
1) Make the field thats unique as your key - best way CB server respects this.
1) write your validator that checks against document for the field that needs to be unique.
2) use the Refdoc, but it comes with extra caution that you need to take. For instance there is no guarantee that someone can write an update document or any ottoman bulk operation feature (that uses n1ql behind the scene) to quickly break the integrity of uniqueness.

Hope this helps !

**Comment by bwgjoseph** [comment]
In that case, can I also suggest to add in to the docs of what is supported by `Ottoman`? So that I can know what is there out-of-the-box and what are the ones that I need to implement myself.

And hopefully, I can put up some feature request to have `Ottoman` add more support out-of-the-box (depending on the current list) in the future. Will discuss further once the supported list is out.

---

Also, to clarify, in case you misunderstood earlier from my post that when I mentioned `String, Number and Date`, I am referring to the options such as `uppercase, lowercase, min, max, minLength, maxLength, enum, etc` and not the `Type`

**Comment by bwgjoseph** [comment]
From our current test, it seem that `min, max, enum, default, required` are support, but `minLength, maxLength` are not. Haven't test all the others yet

**Comment by AV25242** [comment]
@bwgjoseph  I need some clarification here.  You are correct not all of these are directly supported, however like discussed you can accomplish these by wiring it up with hooks. As we evolve Ottoman we can discuss about adding these features. 

Also on adding to the documentation, this [section](https://v2.ottomanjs.com/classes/datetype.html#accessors) talks about what are the different assessors available, let me know if i am missing something ?

**Comment by bwgjoseph** [comment]
Alright, I was actually looking at [schema-doc](https://v2.ottomanjs.com/guides/schema.html) to see the example of what are actually supported because I couldn't find any other docs that mention it

I can do a search, but it doesn't show all the options as well

![image](https://user-images.githubusercontent.com/37484538/100758712-c72fc700-342a-11eb-88a0-774aa385db50.png)

On the API dropdown,

![image](https://user-images.githubusercontent.com/37484538/100758742-d0b92f00-342a-11eb-8648-8f9957a6bf59.png)

So I'm not sure how you manage to navigate to the `DateType` API page

Not sure if I'm missing something obvious as well not

---

With that, can I also check what does [auto](https://v2.ottomanjs.com/interfaces/coretypeoptions.html#optional-auto) does/mean?

**Comment by AV25242** [comment]
@bwgjoseph  auto generates a UUID which is normally the key in documents. This was a feature that existed in Ottoman V1.

**Comment by bwgjoseph** [comment]
I still don't quite understand.  

It is an optional field, and currently, a UUID is being generated without defining any `auto` option. So what does it mean to define an `auto` option?

```
const schema = new Schema({
  id: {
    type: string,
    auto: // what to set here?
  },
  // I can use for other fields?
  myNumber: {
    type: number,
    auto: // what does it mean if I set here?
  }
});
```

and since that `auto` is part of the `CoreTypeOptions`, which means it is available for all fields, not just for `id`?

So lastly, how does it diff from using `default` if you said that it is used for generating UUID.

```
const schema = new Schema({
  id: {
    type: string,
    default: () => randomString() // or () => uuid()
  },
});
```

**Comment by AV25242** [comment]
@bwgjoseph  default is to set default value, auto is to generate UUID for the documents key / id. Every document must have a Key which usually you would provide and will be meaningful for instance a key could be  customername::phonenumber 
so that is a custom key
if you dont have a usecase of custom key (which most of the customer have the use case very rare you will not but possible)
then you can do a id with auto. Its strictly a string you tie it with a number it will fail or should fail.

hope this helps/

**Comment by bwgjoseph** [comment]
hmm, it does help but I think it's still a little unclear of the exact difference between both. I might still not getting it though, hence, my confusion. 

```js
const schema = new ottoman.Schema({
	id: { type: String, default: () => 'mycustom::id' },
	name: { type: String, auto: () => new Date() },
        test: { type: String, auto: 'uuid' },
	date: { type: Date } });
const DummyDate = ottoman.model('DummyDate', schema);
const result = await DummyDate.create({ date: new Date('10 Dec 2020 00:00') });
console.log(result);
```

```
// output
_Model {
  date: 2020-12-09T16:00:00.000Z,
  id: 'mycustom::id',
  name: 'Fri Dec 04 2020 14:18:28 GMT+0800 (Singapore Standard Time)',
  test: 'c805d9df-ff46-4fce-9ff7-69300880788c',
  _type: 'DummyDate',
  _scope: '_default'
}
```

Looking into the [source code](https://github.com/couchbaselabs/node-ottoman/blob/c66b36e7d994e09eaeff0211e5b707b4bde6bc23/src/schema/types/core-type.ts#L43-L53)

So based on that, some feedback

1. `auto` is not mentioned anywhere in the doc
2. doc should probably mention that both `default` and `auto` cannot be define together
3. seem like I can pass in `uuid` to `auto` which it will generates uuid string which should also be mentioned in the doc? Seem like a hidden feature

Hence, my confusion comes where my interpretation is that I can use both `auto` and `default` interchangeably. Not sure when one should be use over another? Or what's the pros/cons each provide.

Thanks!

**Comment by AV25242** [comment]
@bwgjoseph  very valid confusion  👍    lets take care of this

**Comment by AV25242** [comment]
its a documentation issue which I will be adding to #319

`auto` is a String Type and will generate a UUID.
 `default` is to assign default values to the field. If you want to use default value as UUID then use `auto` instead.
`auto` and `default` can be used together, but `auto` will take the precedence over `default`

**Comment by bwgjoseph** [comment]
Alright, so

1. Looking at [this](https://github.com/couchbaselabs/node-ottoman/blob/c66b36e7d994e09eaeff0211e5b707b4bde6bc23/src/schema/types/core-type.ts#L48), it will coerced any `function` defined in `auto` to be a `string` . So you could still use `auto` to generate any string as I demo above
2. As mentioned, I can still use both interchangeably and both works whether I'm using `auto` or `default` to generate default value. I mean, the docs can mentioned so what you said - `default is to assign default values to the field. If you want to use default value as UUID then use auto instead.` - but in reality, I still can do otherwise since it's not blocked in code level
3. According to [this](https://github.com/couchbaselabs/node-ottoman/blob/c66b36e7d994e09eaeff0211e5b707b4bde6bc23/src/schema/types/core-type.ts#L58), you cannot use use together unless I'm mistaken?

**Comment by AV25242** [comment]
Yeah agreed to all of your points, on 3 thats interesting :)

**Comment by bwgjoseph** [comment]
The outstanding issue here are:

1. The `Class` [documents](https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/19#issuecomment-736622219) are still not accessible via API dropdown in the documentation site
2. `auto/default` still not mentioned/explained in the doc
3. [this-comment](https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/19#issuecomment-739129714)
4. Any chance to support `uppercase/lowercase/minLength/maxLength` out-of-the-box?

**Comment by AV25242** [comment]
@bwgjoseph  will get back to the team on 1,2,3 on 4 ATM we will not be supporting this but will add to the backlog for future releases (post GA).

**Comment by bwgjoseph** [comment]
Noted, although we hope that number 4 will be able to come sooner

**Comment by AV25242** [comment]
@bwgjoseph 
1 - The Class documents are still not accessible via API dropdown in the documentation site
      **A document API link will be added.**
      
2 -   auto/default still not mentioned/explained in the doc - **_Still waiting_**

3 - Any chance to support uppercase/lowercase/minLength/maxLength out-of-the-box?  - An issue has been [created](https://github.com/couchbaselabs/node-ottoman/issues/351)  and we will work on it once the issues in this iteration are solved.

**Comment by httpJunkie** [comment]
This has been fixed in the documentation for alpha.19

lowercase: boolean, whether to always call .toLowerCase() on the value. (applicable only to string)
uppercase: boolean, whether to always call .toUpperCase() on the value (applicable only to string)
trim: boolean, whether to always call .trim() on the value (applicable only to string)
minLength: Number, creates a validator that checks if the value length is not less than the given number
maxLength: Number, creates a validator that checks if the value length is not greater than the given number
