### ISSUE TITLE
connect to scope and collection

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#2]
In my current setup, I have enabled developer preview for scope and collection. See [setup-couchbase.sh](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/scripts/setup-couchbase.sh). Now, using the demo code taken from [01-create-and-save](https://github.com/httpJunkie/ottoman-demo/blob/master/scripts/01-create-and-save.js) which is current saved as `index.js`. It will throw error as shown below

```
$ node index.js
Saving Document: Couchbase Airlines
CollectionNotFoundError: collection not found
    at _getWrappedErr (Z:\mongoose-vs-ottoman\node_modules\couchbase\lib\errors.js:836:14)
    at Object.wrapLcbErr (Z:\mongoose-vs-ottoman\node_modules\couchbase\lib\errors.js:1009:20)
    at Z:\mongoose-vs-ottoman\node_modules\couchbase\lib\collection.js:572:24 {
  cause: LibcouchbaseError { code: 211 },
  context: KeyValueErrorContext {
    status_code: 4,
    opaque: 2,
    cas: CbCas { '0': <Buffer 00 00 00 00 00 00 00 00> },
    key: '_default$Airline::4a3b849f-6cb2-451e-b577-58afd7195f4a',
    bucket: 'testBucket',
    collection: 'Airline',
    scope: '_default',
    context: '',
    ref: ''
  }
}
```

However, if I did not enable the preview, it will save as expected

```
$ node index.js
Saving Document: Couchbase Airlines
Document: 6cbd3cbd-8f49-46ce-bdca-d9b71cb43734 has been saved
```

Any idea what could be causing it?

**Comment by bwgjoseph** [comment]
@AV25242 replied

Yes, as it stands today (subject to change we can talk about it in our next meeting) determining if scopes and collections are enabled is configuration driven.

look at this example instead : https://github.com/httpJunkie/ottoman-demo/blob/with-scopes-and-collections/scopes-and-collections/01-create-with-id-and-save.js

Same repo different branch that has examples with Scopes and Collections Enabled.

**Comment by bwgjoseph** [comment]
I have used that, and made some minor adjustment... The data seem to be created, but not sure how I can view it.

This is what I have.

<details>
 <summary>Click to view script</summary>

```js
const ottoman = require('ottoman')
const { model, Schema } = require('ottoman')

// create connection to database/bucket
ottoman.connect({
  connectionString: 'couchbase://localhost',
  bucketName: 'testBucket',
  username: 'user',
  password: 'password'
})

const schema = new Schema({
  callsign: String,
  country: String,
  name: String,
  airlineId: String
})

schema.index.findByName = {
  by: 'name',
  type: 'refdoc'
}

// create model representing our airline
const Airline = model('Airline', schema, {
  // added scopeName
  scopeName: 'testScope',
  collectionName: 'testCollection',
  idKey: 'airlineId'
})

// Creating a use that matches the model
const united = new Airline({
  callsign: 'Couchbase',
  country: 'United States',
  name: 'Couchbase Airlines',
  airlineId: 'airline_couchbase'
})

// run the query
const runAsync = async() => {
  try {
    await united.save()
  } catch (error) {
    throw error
  }
}

let useCollections = true
ottoman.start({useCollections})
  .then(() => {
    runAsync()
      .then(async () => {
       // added to print out result, but nothing gets printed
        const options = { consistency: ottoman.SearchConsistency.LOCAL };
        const result = await Airline.find({}, options);
        console.log(`success: airline added`, result)
        process.exit(0)}
      )
      .catch((error) => console.log(error))
  })
```

</details>

So what I did was to change to use my `bucketName, and collectionName`.

This is the output

```js
$ node index2.js
collection created: _default/testCollection
success: airline added
```

However, there doesn't seem to have any way to view on the UI

![image](https://user-images.githubusercontent.com/37484538/98964012-45433100-2543-11eb-80b5-4318a28007d5.png)

After which, I added `scopeName` options, and did the same. The UI still does not display anything but using `cbstats` command, I am able to view that there is docs inside, but I'm not quite sure how to view the docs using cli command.

```
root@2422e9a48e22:/scripts# /opt/couchbase/bin/cbstats -u admin -p password -b testBucket localhost:11210 collections
 collection:0x0:items:         0
 collection:0x8:items:         2
 manifest:collection:0x0:name: _default
 manifest:collection:0x8:name: testCollection
 manifest:collections:         2
 manifest:default_exists:      true
 manifest:uid:                 2
```

---

A side note, if you see the script above, I also added a `find()` command to get the data, but nothing gets printed out.

```
// This is the output

$ node index2.js
success: airline added {
  meta: {
    requestId: '1b2ba7f5-81a5-4d78-a6b7-be9a3754c5fb',
    clientContextId: 'a4d22acaeb92df53',
    status: 'success',
    signature: { '*': '*', _type: 'json' },
    profile: undefined,
    metrics: {
      elapsedTime: 19.4906,
      executionTime: 19.4417,
      sortCount: undefined,
      resultCount: 0,
      resultSize: 0,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: []
}
```

---

So question is

1. The UI currently doesn't support viewing of scope/collection data?
2. How to perform a find for the data that exist in scope/collection?

Thanks

**Comment by AV25242** [comment]
Yeah 6.6 is Developer Preview as you know and the UI isn't still updated. But in few weeks  (probably Bobby can update you on that) 7.0 Beta will be in place and it has all you need in terms of visualization of data via UI

**Comment by AV25242** [comment]
7.0 Beta releases today - just a FYI

**Comment by bwgjoseph** [comment]
Great! Still don't see in the website though, will try it out once it is available publicly.

**Comment by AV25242** [comment]
> Great! Still don't see in the website though, will try it out once it is available publicly.

Yeah COB US check it out !
