### ISSUE TITLE
Reference schemaType

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#23]
Hi,

Is there any sample for [reference](https://v2.ottomanjs.com/guides/schema.html#allowed-schematypes-are) type? 

Also, the [link](https://v2.ottomanjs.com/classes/reference) in the docs brings me to a 404 page for reference.

**Comment by AV25242** [comment]
Yes we have quite a few reference

 1 -  https://github.com/httpJunkie/ottoman-demo/blob/master/scripts/10-referential-integrity.js (from connect)
 2 - https://v2.ottomanjs.com/guides/document.html#populate

The link needs to be fixed thanks,  will report it

**Comment by bwgjoseph** [comment]
Thanks, will take a look.

Consider this issue close (will leave it open for a couple of days for myself)
