### ISSUE TITLE
support for Buffer schemaType

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#24]
Hi,

How do I store binary data? In `mongoose`, we use [Buffer](https://mongoosejs.com/docs/schematypes.html#buffers), but what's the equivalent in `Ottoman` if any?

Thanks

**Comment by AV25242** [comment]
@bwgjoseph  currently we dont have any support for Buffer type.

**Comment by bwgjoseph** [comment]
This is quite important (to us). Would this be supported soon?

**Comment by AV25242** [comment]
Can you share your Usecase please ?

**Comment by bwgjoseph** [comment]
We are storing small files (pdf, etc) on the database

**Comment by AV25242** [comment]
I see

quick question. Since its an opportunity (migration), will it not be a good practice to store PDF / Images on S3 bucket or a storage of your choice and then store the path to it as a string. 

What would be the benefit of storing as buffer ?

**Comment by bwgjoseph** [comment]
Totally agreed! 

But unfortunately, I don't think that migration (to storage buckets) will happen anything soon (due to other factors), so the interim would be storing in database right now

**Comment by AV25242** [comment]
This feature cannot be directly supported via Ottoman for Ottoman being Json in nature and supporting truly Json documents. 

The workaround will be to store documents in S3 or other storage
An alternative would be to store the documents  Couchbase buckets with a Key that can be identified easily by the document created by Ottoman. In that sense the application using Ottoman probably can read and write from the Couchbase bucket directly using Couchbase SDK.

**Comment by bwgjoseph** [comment]
Quick question, is this a limitation in `ottoman` itself, or I can't store `Buffer` type even if using `couchbase nodejs sdk`?

And a quick thoughts, could I do this as a workaround in `ottoman`? Haven't tested though

```js
const buffer = fs.readFileSync('./file.pdf');
const bufferString = buffer.toString('hex/base64'); // store as string
// save to database via ottoman (now a string instead of buffer)
```

So when I fetch back, and before return to client, it could perform some conversion or return as is to client, and let client do the conversion? Could make use of the getter/setter or pre/post hook to do the conversion?

Would that work?

**Comment by brett19** [comment]
Hey @bwgjoseph,
Couchbase itself is capable of storing binary data, but it does make a differentiation between a JSON document and a binary document since it's not possible to directly store binary bytes inside of a JSON blob.  Ottoman makes a specific choice of dealing specifically with JSON, since this is the format that Couchbase uses throughout it's services (such as secondary indexing, views, analytics, etc...).
In terms of possible avenues of attack w.r.t. a solution, you can definitely base64 encode the data and put it directly in your JSON document more or less like you showed in your example.
Cheers, Brett

**Comment by AV25242** [comment]
@bwgjoseph hope the ^^^ was what you were looking for

**Comment by bwgjoseph** [comment]
Hi @brett19 and @AV25242 

Thanks for the explanation, I'll discuss internally with my team to see how best we can do this in the future. Will keep this issue open, and post more question here as we move on
