### ISSUE TITLE
support for Any (Mixed) schemaType

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#25]
Hi,

How do I store `any` for a particular field? In `mongoose`, we use [Mixed](https://mongoosejs.com/docs/schematypes.html#mixed) to defined a field can be used to store anything by declaring something like

```js
// all means the same
const Any = new Schema({ any: {} });
const Any = new Schema({ any: Object });
const Any = new Schema({ any: Schema.Types.Mixed });
```

Is there any equivalent in `Ottoman`?

**Comment by AV25242** [comment]
@bwgjoseph  AFAIK we dont have any support for Object or Mixed as it stands today

**Comment by bwgjoseph** [comment]
This is somewhat important (to us). Would this be supported soon?

**Comment by AV25242** [comment]
Can you share your usecase please ?

**Comment by bwgjoseph** [comment]
There's a very specific use-case where there are external client calling our API, and they may include certain fields that does not match the schema, and those fields will be placed under the `Mixed` type field. As we do not know the fields before-hand, and if the fields given can't be mapped to the schema, it will be placed inside `c` (mixed)

```js
const schema = {
  a: string, b: string, c: Mixed
}

// sending from external client
const data = {
  a: 'a',
  b: 'c'
  d: 'd',
  e: 1,
}

// mapped to 

const data = {
  a: 'a',
  b: 'c',
  c: {
   d: 'd',
   e: 1,
  }
}

```

I understand it's possible to keep it open (non-strict), and take in whatever was provided but it's not actually "safe", and due to certain requirements/legacy reason, it is designed as such.

**Comment by AV25242** [comment]
Thanks @bwgjoseph  based on the above example, non-strict and Mixed are equally risky  if you were to. 
Just that Mixed wraps it up, but other than that there no difference, may be a nice to have feature.

**Comment by bwgjoseph** [comment]
Yup, but IMO `Mixed` is less risky, and constraint to only a specific field (I dictate) rather than the entire schema

Do discuss with your team, and let us know if this is something that can be supported, and any rough timeline for it

Thanks!

**Comment by AV25242** [comment]
Issue has been created https://github.com/couchbaselabs/node-ottoman/issues/328

**Comment by bwgjoseph** [comment]
I added test for [mixedtype](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/mixed.test.ts)

Mostly seem fine but for adding `Date` to a `MixedType`, the output is a `string` instead of a `Date` type like `scheduledAt` field

Not sure if it should keep the type instead of changing? I thought maybe it should keep the same?
```js
const schema = new mongoose.Schema({ scheduledAt: Date, extension: ottoman.Schema.Types.Mixed });

const data = { scheduledAt: new Date(), extension: new Date());

// after create
scheduledAt is a Date
extension is a string
```

**Comment by AV25242** [comment]
Will get back to you !

**Comment by bwgjoseph** [comment]
Thanks.

I could use a pre-hook that converts `scheduledAt` from `Date` to `string` as well right, if that's what I want to do

**Comment by AV25242** [comment]
@bwgjoseph  that would be right

**Comment by bwgjoseph** [comment]
Thank you!
