### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by AV25242** [bwgjoseph/mongoose-vs-ottoman#27]
Just created this so that we can have a clear path on communication. Please close this once we have agreed on the communication via GitHub-Issues

My thoughts are 

      -  Create a new Issue with something like "New" and  Assign it to me
      -  After every response we can assign issues to each other.
      -  Labels can be used in a way where  we  have most 1 or 2 labels for instance after our back and forth communications
          If I end up creating a ticket I will tag with "issue-created"   - this also means its being worked upon.
          Once the issue is fixed and is a part of new release  I will tag with "await-verification" 
          If we wont fix an issue then I will tag it with "wont-fix"

My bad I was using labels to assign it between you and me, I think the Assignees will be much better. Sorry for the confusion. Its on me. 

Let me know if you are ok with this approach ?

**Comment by bwgjoseph** [comment]
LGTM

**Comment by bwgjoseph** [comment]
@AV25242 I added new label `follow-up` for myself to identify which ones I need to follow up internally later on/in future so issue like #24 can be closed first without hanging in the `open` issues list
