### ISSUE TITLE
ModelOptions

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#28]
Hi,

Seem like the `ModelOptions` for [docs](https://v2.ottomanjs.com/guides/model.html#model-options) isn't updated

```js
export interface ModelOptions {
    collectionName?: string;
    scopeName?: string;
    idKey?: string;
    scopeKey?: string;
    collectionKey?: string;
    maxExpiry?: string;
    keyGenerator?: (params: {
        metadata: ModelMetadata;
        id: any;
    }) => string;
}
```

Missing `maxExpiry`

**Comment by AV25242** [comment]
Thanks @bwgjoseph  added it to the upcoming documentation fix

https://github.com/couchbaselabs/node-ottoman/issues/319

**Comment by bwgjoseph** [comment]
Have verified in the documentation site
