### ISSUE TITLE
keyGenerator

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#29]
Hi,

It can't seem to get `keyGenerator` to work properly. Here's what I did, do let me know if I done it wrongly.

```js
const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${metadata.collectionName}::${id}`;
const idKey = 'customGKey';
const schema = new ottoman.Schema({
	id: { type: String, default: () => 'mycustom::id' }});
const generator = ottoman.model('DummyDate', schema, { keyGenerator, idKey });
await generator.create();
```

I used the test written in `node-ottoman` - https://github.com/couchbaselabs/node-ottoman/blob/c66b36e7d994e09eaeff0211e5b707b4bde6bc23/__test__/model-crud.spec.ts#L237-L250

Here's my output

```js
_Model {
  _scope: '_default',
  _type: 'DummyDate',
  // generated value is not what is defined?
  customGKey: '645f6267-2a4c-4ff0-a0a3-5099402d46dc',
  id: 'mycustom::id'
}
```

Added [test](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/key-generator.test.ts)

**Comment by AV25242** [comment]
Hi @bwgjoseph  will get back to you

**Comment by AV25242** [comment]
@bwgjoseph  have added this to the docs update ticket #319

**Comment by bwgjoseph** [comment]
Alright, I tried it out, and it is indeed the case. Thanks for clarifying.

I still am slightly confused between `document.key`, and `document.value.id` Do bear with me as Couchbase is still pretty new to me.

How do I run a find against `meta().id`? Can I issue such query through `ottoman` or do I need to issue through `n1q1`? Because from what I understand (correct me if I'm not), if I were to search using `meta().id`, it is much faster than searching against `document.value.id` right?

Looking back at [nodejs-sdk](https://docs.couchbase.com/nodejs-sdk/current/howtos/kv-operations.html), are all the examples where it state `key`; are referring to `document.key`? Such as `const result = await collection.insert(key, document);`. If that is the case, then it means `ottoman - model.findById(id)` is referring to the `document.value.id` and it doesn't expose a way to get by `document.key` (my question above)?

**Comment by AV25242** [comment]
How do I run a find against meta().id ? 

     You can use n1ql yes thats a way
     from find like above use the [select options  ](https://v2.ottomanjs.com/classes/findoptions.html#optional-select)
      `const options = { select: 'meta().id,travel-sample.*', consistency: SearchConsistency.LOCAL }`

   I am not clear with your other question on key vs id, both are same used interchangeably, when you create a document by using insert you will provide a key and thats what you use to find when you do findbyid ( probably you are confused by the name? findbykey )

**Comment by bwgjoseph** [comment]
Ah, sorry for the confusion. Let me try to clear it up.

I think you got me wrong (or maybe its me?), I'm not asking to select the property/field for `meta().id` as part of the response in `find()` but to query using `document.key`.

So in this case, our generate doc look something like

```js
// so meta.id is my document key
{
  "meta": {
    // I refer this as meta.id below
    "id": "_default$Airplane::bce7c9cc-ba24-4d2c-953c-8de56a2475e0",
    "rev": "1-164d98cf59c900000000000002000000",
    "expiration": 0,
    "flags": 33554432,
    "type": "json"
  },
  "xattrs": {}
}

// and this is the document value
{
  "callsign": "Hawk",
  "name": "Couchbase Airlines",
  "operational": true,
  "destination": [
    "Japan"
  ],
  "scheduledAt": "2020-11-20T03:30:00.000Z",
  "capacity": 250,
  "model": "A380",
  "size": "S",
  "info": {
    "firstFlightAt": "2010-01-12T05:10:00.000Z",
    "numberOfFlightsSince": 10000
  },
  // I refer this as document.id below
  "id": "bce7c9cc-ba24-4d2c-953c-8de56a2475e0",
  "_type": "Airplane",
  "_scope": "_default"
}
```

So `ottoman` has a `findById(id)` method, so if I wanted to find a particular doc by id, I can issue a query by `Model.findById(document.id)` and this will return me my doc. Now, what if I want to query to find the document by `key`? Can I issue a query like `Model.findByKey(meta.id)`?

Also in particular, and I refer to [crud-ops-get](https://docs.couchbase.com/nodejs-sdk/current/howtos/kv-operations.html#retrieving-full-documents) example.

Where it states `const result = await collection.get(key);` where I'm assuming that the `key` here is referring to `meta.id` and not `document.id`

So I'm still trying to wrap my head around when do I need to query against `meta.id` and `document.id`? What's the use-case and so on. I mean, generally, when using `ottoman`, I probably be using `findById(document.id)` most of the time, but I want to know what's the other use-case to do a `findByKey(meta.id)` as well

---

> when you create a document by using insert you will provide a key and thats what you use to find when you do findbyid

If using `ottoman`, there's only `create` and not `insert`. `insert` is when using the `nodejs sdk`?

So look at my [create.test.ts](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/379e977ec6697864ca51e969423ba413f332af45/test/ts/create.test.ts#L19), when using `ottoman`, by default, since the `uuid` is generated to `id` field, and the `document.key` is also auto generated, there's no key to be provided. And even when using the `keyGenerator` to override the key generation, using `findById` is not passing in the `document.key` as shown in the example above.

---

Side question:

Although it's nice to know that I can do `{ select: 'meta().id,travel-sample.*' }`, can I just do `{ select: 'meta().id, *'}` without the `bucket` name? Also, does it have to be `bucket` name? What if this is a scope/collection? I actually would rather to place just `*` though

Hope this clears up more, and let me know if I'm still not putting my point across.

Thanks!

**Comment by bwgjoseph** [comment]
After our discussion earlier so, my understanding (please correct me if I'm wrong), is that when I run `findById(id)`, `ottoman` will call the underlying KV operation to grab the value via `key`.

```js
// example
const find = ottoman.findById('12345');

// underlying, it will know how to construct `prefix` of the `meta.id` which could be `default:;default::` and concat with the `id` given which will gives
const find = kv.get(default::default::12345)
```

With that (if I am right on the above), I have some further queries...

So we are allowed have a custom `keyGenerator` function, and a custom `id` generator. In such case, there is no guarantee that `ottoman` is able to construct the `key` back?

```js
// example
const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::random::${random()}`; // output: gen::random:11111
const idKey = 'customGKey';
const schema = new ottoman.Schema({
	id: { type: String, default: () => anotherRandom() }}); // output: 22222
```

In this case, since both `random()` and `anotherRandom()` both gives different value, how does `ottoman` query by the `key`?

Or it could even be the sequence is different..

```js
// example
const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${id}::${scopeName}`; // output: gen::645f6267-2a4c-4ff0-a0a3-5099402d46dc::myScope
const idKey = 'customGKey';
const schema = new ottoman.Schema({
	id: { type: String, auto: () => 'uuid' }}); // output: 645f6267-2a4c-4ff0-a0a3-5099402d46dc
```

So how would `ottoman` construct back to the `key` as well?

---

Also, I have moved the `$select` question above to #31 as to not mix the concern

**Comment by httpJunkie** [comment]
Still looking into this issue...

**Comment by bwgjoseph** [comment]
As suspected, in the first example stated above, `ottoman` will not be able to get back the doc, and probably will never have any way to get it back. And also mentioned before, this is something a developer probably wouldn't do since it doesn't make sense, but if there is some way to detect and maybe warn developer if they do this (either in API or docs) then it would be good

```js
const random = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
const generated = random();

const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${metadata.collectionName}::${random()}`;
const schema = new ottoman.Schema({
	id: { type: String, default: () => generated }});
const generator = ottoman.model('DummyDate', schema, { keyGenerator });
await generator.create();
const options = { select: ['meta().id', '*'], consistency: SearchConsistency.LOCAL }
const doc = await generator.find({}, options);
assert.strictEqual(doc.rows.length, 1);
await generator.findById(generated, { consistency: SearchConsistency.LOCAL }); // searching for id = l5qewpmx1qbkfz2x0hhpqf
```

This is the actual doc generated

```js
{
  "meta": {
    "requestId": "c1bf5431-da49-4360-8a97-ee060cf002aa",
    "clientContextId": "c0b09cbc0edbd11b",
    "status": "success",
    "signature": {
      "*": "*",
      "_type": "json",
      "id": "json"
    },
    "metrics": {
      "elapsedTime": 23.6639,
      "executionTime": 23.6045,
      "resultCount": 1,
      "resultSize": 162
    }
  },
  "rows": [
    {
      "_type": "DummyDate",
      "id": "gen::_default--DummyDate::bxpjs8oqof6kuby8u1imsg",
      "testBucket": {
        "id": "l5qewpmx1qbkfz2x0hhpqf",
        "_type": "DummyDate",
        "_scope": "_default"
      }
    }
  ]
}
```

---

For the second case, it is able to grab back the document though. I thought that it shouldn't be able to search back based on previous discussion. 

```js
const random = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
const generated = random();

const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${generated}--${metadata.collectionName}::`;
const schema = new ottoman.Schema({
	id: { type: String, default: () => generated }});
const generator = ottoman.model('DummyDate', schema, { keyGenerator });
await generator.create();
const options = { select: ['meta().id', '*'], consistency: SearchConsistency.LOCAL }
const doc = await generator.find({}, options);
assert.strictEqual(doc.rows.length, 1);
await generator.findById(generated, { consistency: SearchConsistency.LOCAL });
```

```js
// this returns from find
{
  "meta": {
    "requestId": "149c2eeb-e6f3-415a-8686-45135e216537",
    "clientContextId": "6c3349be47c41a4d",
    "status": "success",
    "signature": {
      "*": "*",
      "_type": "json",
      "id": "json"
    },
    "metrics": {
      "elapsedTime": 18.1138,
      "executionTime": 18.0494,
      "resultCount": 1,
      "resultSize": 164
    }
  },
  "rows": [
    {
      "_type": "DummyDate",
      "id": "gen::_default--itos3shm929ffabwn91zip--DummyDate::",
      "testBucket": {
        "id": "itos3shm929ffabwn91zip",
        "_type": "DummyDate",
        "_scope": "_default"
      }
    }
  ]
}

// this returns from the findById
_Model {
  id: 'itos3shm929ffabwn91zip',
  _type: 'DummyDate',
  _scope: '_default'
}
```

**Comment by httpJunkie** [comment]
The keyGenerator function needs to be a pure function, It will always return the same value if you provide the same arguments.

If you use `random()` function,  keyGenerator will have a side-effect and not will return the same value for the same arguments.

Then Ottoman will not be able to retrieve documents

**Comment by josephstgh** [comment]
Sorry, there's a flaw in my test. Will run the test again to verify

**Comment by bwgjoseph** [comment]
So I wrote this new test

```js
const g = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${g()}--${metadata.collectionName}::`;
const schema = new ottoman.Schema({
	id: { type: String, default: () => g() },
	name: { type: String },
});
const generator = ottoman.model('DummyDate', schema, { keyGenerator });
await generator.create(new generator({ id: '1', name: 'a' }));
await generator.create(new generator({ id: '2', name: 'b' }));
await generator.create(new generator({ id: '3', name: 'c' }));
const options = { select: ['meta().id', '*'], consistency: SearchConsistency.LOCAL }
const doc = await generator.find({}, options);
console.log(JSON.stringify(doc, null, 2));
console.log(await generator.findById('2'));
```

And when I run a find, the doc returns

```js
{
  "meta": {
    "requestId": "2d352c8b-ab19-4e09-bb2e-6eb951d44011",
    "clientContextId": "72ccc6019a4320c9",
    "status": "success",
    "signature": {
      "*": "*",
      "_type": "json",
      "id": "json"
    },
    "metrics": {
      "elapsedTime": 10.7656,
      "executionTime": 10.6587,
      "resultCount": 3,
      "resultSize": 398
    }
  },
  "rows": [
    {
      "_type": "DummyDate",
      "id": "gen::_default--j8gwrenj8jdpiu8ymtdy7--_default::",
      "testBucket": {
        "id": "1",
        "name": "a",
        "_type": "DummyDate"
      }
    },
    {
      "_type": "DummyDate",
      "id": "gen::_default--m9ik3arlvpjzvcvewtlgxl--_default::",
      "testBucket": {
        "id": "2",
        "name": "b",
        "_type": "DummyDate"
      }
    },
    {
      "_type": "DummyDate",
      "id": "gen::_default--q94jaezykhq2ozt1pgvtlq--_default::",
      "testBucket": {
        "id": "3",
        "name": "c",
        "_type": "DummyDate"
      }
    }
  ]
}
```

And the `findById` will throws 

```js
1) test keyGenerator function
   gh-#29 p3:
 Error: document not found
  at _getWrappedErr (node_modules\couchbase\lib\errors.js:856:14)
  at Object.wrapLcbErr (node_modules\couchbase\lib\errors.js:1009:20)
  at Z:\mongoose-vs-ottoman\node_modules\couchbase\lib\collection.js:237:24
```

And I'm using `alpha.12`. Hope I didn't make any mistake this time.

**Comment by AV25242** [comment]
@bwgjoseph  for you to understand what is going on lets step back 
if you dont use any key generator an id field is created for you and thats the same as the Key for the document 
remember findbyid is actually finding by the key of the document  and so passing in that id works.
in case of a keygenerator you are not forcing to generate a key that you want so you will now have to call findbyid by passing in that key , in this case you are calling findbyid by passing in '2' which is not the key of the document.

**Comment by bwgjoseph** [comment]
Thanks! I have to clarify that I (think I) understand how it works now, but given that it doesn't stop me from doing so, and I think the documentation don't really mention this, I thought this might be confusing... or it could be just me

> remember findbyid is actually finding by the key of the document and so passing in that id works.

I think this is the confusing part (as mentioned) where I can generate a different `key` and `value.id`, and naturally, given the method is called `findById`, I would assume (as a developer) that to be using `value.id` to find, instead of `key`

Which brings me to the point where I find there should never be a scenario where you define the `keyGenerator` and also either 

1. define a `id` yourself
2. or use a `default()` to generate the `id`
3. or let `ottoman` to generate the uuid

I quote

> in case of a keygenerator you are not forcing to generate a key that you want so you will now have to call findbyid by passing in that key , in this case you are calling findbyid by passing in '2' which is not the key of the document.

Given that I create a document with self generated id, and using keyGenerator. Then query for a document, and then use the document to query using `findById`, it will not return me any document

```js
{
  "_type": "DummyDate",
  "id": "gen::_default--zo0wm03vrjt2wpltd7vak--_default::",
  "testBucket": {
	"id": "1",
	"name": "a",
	"_type": "DummyDate"
  }
}

// find all
const docs = model.find();

// findone
// it's a very simple example but hope to illustrate the point
const doc = model.findById(docs.testBucket.id);
```

Hope I'm still making some sense here. I guess as long as the documentation did state up front on the usage, it should be fine.

---

I just tried something and it works but I'm not sure why though

```js
const g1 = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${g1}--${metadata.collectionName}::`;
const schema = new ottoman.Schema({
	id: { type: String },
	name: { type: String },
});
const generator = ottoman.model('DummyDate', schema, { keyGenerator });
await generator.create(new generator({ id: '1', name: 'a' }));
const options = { select: ['meta().id', '*'], consistency: SearchConsistency.LOCAL }
const doc = await generator.find({}, options);
console.log(JSON.stringify(doc, null, 2));
console.log(await generator.findById('hello'));
```

This is the result

```js
{
  "_type": "DummyDate",
  "id": "gen::_default--zo0wm03vrjt2wpltd7vak--_default::",
  "testBucket": {
	"id": "1",
	"name": "a",
	"_type": "DummyDate"
  }
}

// and findById('hello') actually returns
_Model { id: '1', name: 'a', _type: 'DummyDate' }
```

**Comment by AV25242** [comment]
@bwgjoseph  on the documentation part, I 100% agree with you and i think the team will ensure keyGenerator is documented properly.

on the `findbyId('hello')` are you sure you dont have a document with id as `hello` ?

**Comment by bwgjoseph** [comment]
Yup, I have tested it again, and this is what is shown in my UI

![image](https://user-images.githubusercontent.com/37484538/104831857-6a4b7b80-58c7-11eb-90be-5b60d23bd7b6.png)

![image](https://user-images.githubusercontent.com/37484538/104831868-86e7b380-58c7-11eb-882b-5ed1bfebee54.png)

![image](https://user-images.githubusercontent.com/37484538/104831875-8bac6780-58c7-11eb-8b73-eba0894d245f.png)


And my result still comes back with the document as mentioned previously

**Comment by AV25242** [comment]
@bwgjoseph  Keygenerator explaination is now simplified and a new doc page has been added see this

https://v2.ottomanjs.com/advanced/how-ottoman-works.html

**Comment by bwgjoseph** [comment]
I read the documentation, and I think it's alright. But the issue above (https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/29#issuecomment-755430502) is still not answered yet.

Calling `generator.findById('hello')` still returning me data that is wrong

**Comment by AV25242** [comment]
@bwgjoseph that was because of the key-generator behavior where you were allowed to explicitly set the id. In the new way you should not be able to unless you override the default id by setting the idkey. 

in nutshell the above should be obsolete

**Comment by bwgjoseph** [comment]
I just tested with alpha.18, and it now does not return me any document, and throws 'document not found'. I think it's good now. I will update my test case later, and verify again before closing this
