### ISSUE TITLE
docs for connecting to scope/collection

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#3]
How do I specify in the connection to connect to a specific scope/collection? I see there is some [configurationOptions](https://v2.ottomanjs.com/guides/connections.html#global-config) but don't really understand what does each of them mean. Would it be better to explain those options in the doc, and/or have a link to somewhere if there is a explanation elsewhere?

**Comment by bwgjoseph** [comment]
@AV25242 replied

You are right, the global configuration is not well defined. We will reach out to the team and ask them about it. Also looks like the global settings doesnt       allow you to specify defaultCollections. We will have to get back to you on this but in the meanwhile you can try and see if this works

```js
const { setGlobalConfig } = require('ottoman')

ottoman.globalConfig({ defaultScope: '<YOUR_SCOPE_NAME>' })
```

**Comment by AV25242** [comment]
I will be creating a ticket with the team to handle this.

You should be able to provide a globalconfiguration where you can provide the defaultScope and defaultCollection and further you should be able to override it at the model level.

**Comment by bwgjoseph** [comment]
That sounds great!

Thank you

**Comment by AV25242** [comment]
Tickets have been created

**Comment by AV25242** [comment]
@bwgjoseph  https://github.com/couchbaselabs/node-ottoman/issues/309 should take care of this.

**Comment by bwgjoseph** [comment]
Docs did indicate via `OttomanConfig` now - https://v2.ottomanjs.com/guides/ottoman.html#ottoman-constructor-options

So will close this
