### ISSUE TITLE
Any way to set global SearchConsistency 

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#32]
Hi,

Is there any way to set global config for `SearchConsistency`? And override when required?

For example, in current [global-config](https://v2.ottomanjs.com/guides/connections.html#global-config), it has some fields that can be defined but I don't see `SearchConsistency`.

```js
// example
import {globalConfig} from "./ottoman";

globalConfig({
    SearchConsistency: 'SearchConsistency.LOCAL',
  });
```

So the idea is to allow me to put a default `SearchConsistency` so that I don't have to set it at every `find`

```js
// I don't have to define at every `find`
const find = await Airplane.find(
	{},
	{
		consistency: SearchConsistency.LOCAL
	}
);
```

If I set as the global config, I can then just

```js
const find = await Airplane.find(); // SearchConsistency.LOCAL is auto inferred from the global config
```

But I can override if I want to, although I'm not sure if there will be such use-case

```js
// like so
const find = await Airplane.find(
	{},
	{
		consistency: SearchConsistency.GLOBAL
	}
);
```

Thanks

**Comment by AV25242** [comment]
Agreed ! Issue has been created https://github.com/couchbaselabs/node-ottoman/issues/331

**Comment by bwgjoseph** [comment]
Is this ready for testing? If so, how do I set it? I can't seem to find in the documentation

**Comment by AV25242** [comment]
interesting, this is moved to closed in my kanban, I will reach out.

**Comment by bwgjoseph** [comment]
Thanks, will verify this

**Comment by bwgjoseph** [comment]
Have tested this, but it looks like the configuration is not being passed over to `getDefaultInstance`

Take a look at this `global.test.ts`, specifically

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/50ae9cf04c843c0c90d6f0028c741a5dbf0853d3/test/ts/global.test.ts#L76

I logged out the `config` and realize that whatever `SearchConsistency` option I have passed in, is not reflected in the `getDefaultInstance` config

```js
// from initOttoman
{ collectionName: '_default', searchConsistency: 1 }
// from getDefaultInstance
{ collectionName: '_default' }
```

I did not test for the rest of the config and see if they get passed to `getDefaultInstance` as well

I understand there could have multiple instance, so I think the config needs to pass to the different connection (if any) correctly as well

**Comment by bwgjoseph** [comment]
@AV25242 

This is a mistake on my part, I forgot that I had another connection being initialize. So getting the `defaultInstance` is actually another instance, and not the one I'm testing.

Have re-wrote the test, and it seem that all are working as expected
