### ISSUE TITLE
alpha.11 upgrade

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#36]
Hi,

I just tried to upgrade to `alpha.11` and have some errors thrown. I'm listing those that I saw now, I'm not sure if these are intending behavior/changes and if there are others. 

---

1. removeById and [$select](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/%24select.test.ts) throws same type of error

Looking at my current [removeById](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/removeById.test.ts) test, I changed the API from `remove` to `removeById` and it throws this 

```js
 1) test removeById function
       ottoman - should remove doc:
     Error: Property callsign is required, Property name is required, Property model is required
      at Schema.cast (node_modules\ottoman\src\schema\schema.ts:115:13)
      at Object.castSchema (node_modules\ottoman\src\schema\helpers\fn-schema.ts:136:18)
      at new _Model (node_modules\ottoman\src\model\create-model.ts:94:26)
      at Function._a.removeById (node_modules\ottoman\src\model\create-model.ts:202:24)
      at Z:\mongoose-vs-ottoman\test\ts\removeById.test.ts:22:24
      at step (test\ts\removeById.test.ts:33:23)
      at Object.next (test\ts\removeById.test.ts:14:53)
      at fulfilled (test\ts\removeById.test.ts:5:58)
```

---

2. `findById` does not take in `consistency` option

I was able to pass `consistency` option when I'm using `findById` previously

```js
const find = await generator.findById(generated, { consistency: SearchConsistency.LOCAL });
```

But now it complains...

```js
test/ts/key-generator.test.ts:64:60 - error TS2345: Argument of type '{ consistency: ottoman.SearchConsistency; }' is not assignable to parameter of type 'FindByIdOptions'.
  Object literal may only specify known properties, and 'consistency' does not exist in type 'FindByIdOptions'.

64         const find = await generator.findById(generated, { consistency: SearchConsistency.LOCAL });
```

Which is interesting because when I tried to trace through the source code, it seem like it was never supported in the first place, but it didn't throw any error previously. Shouldn't `consistency` be part of the option for `findById`? Or is it not required for `findById`?

---

3. date return type - this is linking back to issue #21

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/3dfa9c5480f5d504772490509ec66119bdbe19cf/test/ts/gh-%2321.test.ts#L24-L28

What's the final decision on the return type? It is still inconsistent..

---

4. `create` now requires arg

Previously, I could call `.create()` without passing in arg like such

```js
const keyGenerator = ({ metadata, id }: {
	metadata: ModelMetadata;
	id: any;
}) => `gen::${metadata.scopeName}--${metadata.collectionName}::${random()}`;
const schema = new ottoman.Schema({
	id: { type: String, default: () => generated }});
const generator = ottoman.model('DummyDate', schema, { keyGenerator });
await generator.create();
```

Now, it throws

```js
TSError: ⨯ Unable to compile TypeScript:
test/ts/key-generator.test.ts:17:25 - error TS2554: Expected 1 arguments, but got 0.

17         await generator.create();
                           ~~~~~~~~

  node_modules/ottoman/lib/types/model/model.d.ts:96:19
    96     static create(data: Record<string, any>): Promise<any>;
                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'data' was not provided.
```

Which I think is fine, but not sure if this is intended behavior with the recent change

I'm currently doing this as a workaround

```js
await generator.create(new generator({}));
```

---

5. parsing failure - error too cryptic?

When I tried to run one `$select` test, and if I specific the connection as such

```js
// like this, it will throw parsing failure (see below)
const ottoman = new Ottoman();
// and not this
const ottoman = new Ottoman({ collectionName: '_default' });
```

```js
1) test $select function
       ottoman - simple $select should be able to work:
     Error: parsing failure
      at _getWrappedErr (node_modules\couchbase\lib\errors.js:830:14)
      at Object.wrapLcbErr (node_modules\couchbase\lib\errors.js:1009:20)
      at Z:\Development\workspace\github\bwgjoseph\mongoose-vs-ottoman\node_modules\couchbase\lib\queryexecutor.js:126:26
```

Maybe there is a way to detect this better, and throw more useful message? I tested for awhile before I realize it since it wasn't very obvious that it is related to the way the connection is init.

4. Documentation

In [defaultInstance](https://v2.ottomanjs.com/guides/ottoman.html#default-ottoman-instance), 

```js
// should it be getDefaultInstance instead?
const defaultConnection = getDefaultInstance();
```

Thanks!

**Comment by AV25242** [comment]
1. removeById and $select throws same type of error - **_This issue was fixed in alpha.12 (Issue has occurred because Model constructor was applying validations)_**

2. Now FindById uses collection.get (KV Operation) function and it does not provide a Search Consistency Option then it was removed, so it should be available immediately i.e its immediately consistent

3. In version alpha.12 should work ok. result.date instanceof Date === true

4. Model.create require 1 argument, this argument is the document to be created. (I don't know why it works without argument, the parameter always was required this code wasn't changed since the very beginning). **_So please pass in the argument_**

5. Since version alpha.11 the method getDefaultConnection does not exist anymore instead you can use getDefaultInstance. The connection concept was encapsulated into the Ottoman class and now users should work with Ottoman instances instead of Connections.
About the cryptic error:
"Error: parsing failure"
It's an error throw from Couchbase SDK 3, It's cryptic for Ottoman too, we will  see what can be done from Nodejs SDK stand point.

**Comment by httpJunkie** [comment]
Alpha 12 is now available Joseph!

**Comment by josephstgh** [comment]
Do you have the changelog for that?

**Comment by bwgjoseph** [comment]
I have verified 1, 2, 3, and 4 using `alpha.12` and it seem to be working fine now

Noted on 5
