### ISSUE TITLE
Get existing Model

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#38]
Hi,

As described in [get existing model](https://v2.ottomanjs.com/guides/model.html#getting-existing-models), when I tried to grab it, it will throw error since the signature returns a void

![image](https://user-images.githubusercontent.com/37484538/103786646-9ec56900-5077-11eb-8d19-27f521a64cce.png)

**Comment by AV25242** [comment]
We are looking into this, thanks much @bwgjoseph

**Comment by AV25242** [comment]
Looks like a defect, will be fixed in the next release.

**Comment by httpJunkie** [comment]
Alpha 13 has been released, please excuse my delay I was out sick.

**Comment by AV25242** [comment]
We have released a new version of our Ottoman V2 NPM package alpha.13 (Compatible with SDK 3.x) and updated the Ottoman V2 documentation site. 

Changelog:
 
CHANGE FEAT: Save when strict set to false #362
ADDED FEAT: Return a GenericManyResponse when batch operations dont match #352
CHANGE FEAT: Fixing getModel to return a Model instance and update doc #350

**Comment by bwgjoseph** [comment]
Please see #39, seem like there's some issue

**Comment by AV25242** [comment]
#39 doesnt seem to be a bug, probably a mis-configuration.

**Comment by bwgjoseph** [comment]
LGTM
