### ISSUE TITLE
API to manage bucket, scope and collection

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#4]
Is there any way to drop a specific bucket/scope/collection? In `mongoose`, I have [dropDatabase](https://mongoosejs.com/docs/api/connection.html#connection_Connection-dropDatabase) and [dropCollection](https://mongoosejs.com/docs/api.html#connection_Connection-dropCollection)

**Comment by bwgjoseph** [comment]
@AV25242 replied

No, there is no explicity Data Definition Languages exposed via Ottoman, is there a specifc usecase that you are targeting? This should be possible via Nodejs SDK. (Need to double check).

**Comment by bwgjoseph** [comment]
This is especially useful in writing test, and seeding database. At least in my experience when working on `mongoose/mongodb`.

I would need to clear the data in the `before` or `beforeEach` when running the test, or I could have a seed-script that drop the entire database/bucket/scope/collection before seeding the dataset.

**Comment by AV25242** [comment]
Tickets have been created to handle this

**Comment by AV25242** [comment]
The following issues should take care of this
https://github.com/couchbaselabs/node-ottoman/issues/306
https://github.com/couchbaselabs/node-ottoman/issues/307
https://github.com/couchbaselabs/node-ottoman/issues/309

**Comment by bwgjoseph** [comment]
Some questions 

1. Are there API to create bucket, scope and collection?
2. What exactly does [collectionManager](https://v2.ottomanjs.com/classes/ottoman.html#collectionmanager), [bucketManager](https://v2.ottomanjs.com/classes/ottoman.html#bucketmanager) do? Is there a `scopeManager`? How is it supposed to be used? I don't think I saw any documentation for this, if I missed out, do point me to the correct link
3. For `ensureCollections` API, does it work like if I were to drop the `scope` and `collection`, and then run `ensureCollections`, would it re-create the `scope` and `collection`? 

Issue / Feedback

1. When I tried to use the `dropCollection` API to drop a invalid collection, it throws `failed to drop collection`. Is that expected? Or should the error be something along, collection does not exist? 

2. If I'm already connected via 

```js
ottoman = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection', searchConsistency });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testDropBucket',
        username: 'user',
        password: 'password'
    });
```

Is it a must for me to pass in the `scope` when removing the collection?

`ottoman.dropCollection('testDropCollection', 'testDropScope');`

Thanks

**Comment by AV25242** [comment]
Sorry I missed this somehow, will get an answer for these.

**Comment by AV25242** [comment]
@bwgjoseph 

**Some questions**

> Are there API to create bucket, scope and collection?

`   Ottoman  has exposed the underlying  nodejs SDK "Managers" for cluster management that will enable you to create bucket scope and collection.`

> What exactly does collectionManager, bucketManager do? Is there a scopeManager? How is it supposed to be used? I don't think I saw any documentation for this, if I missed out, do point me to the correct link

`   https://docs.couchbase.com/sdk-api/couchbase-node-client/CollectionManager.html , now this is the docs for the underlying nodejs sdk, and we will have our documentation updated to refer back to this link in future.`

> For ensureCollections API, does it work like if I were to drop the scope and collection, and then run ensureCollections, would it re-create the scope and collection?

     `Yes that should be the case, let us know if otherwise.`


**Issue / Feedback**

> When I tried to use the dropCollection API to drop a invalid collection, it throws failed to drop collection. Is that expected? Or should the error be something along, collection does not exist?

`You are right, we will add this to basically give back the right error message and exception type that is more appropriate.`


> Is it a must for me to pass in the scope when removing the collection

`    Yes, as at a global level its not guaranteed that the scope name is not overridden and it makes more sense and sort of guarantees that the right collection is being dropped. On the contrary we will eventually add a model level method to drop a collection at that point the scope and collection name will be auto-inferred. `

**Comment by bwgjoseph** [comment]
> Ottoman has exposed the underlying nodejs SDK "Managers" for cluster management that will enable you to create bucket scope and collection.

I assume that `collectionManager` and `bucketManager` is responsible for the management of the bucket, scope and collections. Questions is why does managing buckets is called `bucketManager` and managing scope and collection is called `collectionManager` and not `scopeManager`? I see that `collectionManager` allows you to manage both `scope and collection`. It's a little weird in the API naming, so it's a little confusing

> now this is the docs for the underlying nodejs sdk, and we will have our documentation updated to refer back to this link in future

Yes, definitely

> `Yes that should be the case, let us know if otherwise.`

Yup, will run some test on that soon

**Comment by AV25242** [comment]
Answering to your question above, I would sort of agree that there should have been a scope manager but thats how all SDK's are built today. 

The only item pending here is doc updates  - provide link to these managers. I will assign this to you for testing core functionality. I have opened a ticket for doc updates. let me know if I am missing something ?

**Comment by bwgjoseph** [comment]
Yup, pending item would be doc updates, and my testing.

> but thats how all SDK's are built today.

I'm not sure if I follow you here. My question was why does managing buckets is called `bucketManager` and managing scope and collection is called `collectionManager` and not `scopeManager`? I just want to make sure that I'm not missing anything here

**Comment by AV25242** [comment]
On your question, I dont know why there is no separate scope manager, but what I can tell you is that its not from Ottoman. What you are seeing are the objects that are exposed directly from Node.js SDK. You are absolutely not missing anything here. Collection Manager encompass both Scopes and Collections. Ottoman is just exposing the underlying SDK as is.

**Comment by bwgjoseph** [comment]
Yup, understood! Thanks.

Will run some test on these later on

**Comment by bwgjoseph** [comment]
Some additional feedback/clarification:

1. [node-sdk-api](https://docs.couchbase.com/sdk-api/couchbase-node-client/BucketManager.html) - `getAllBuckets` is not correct.  Doc indicate the API requires to pass in `bucketName` but if you see the [source](https://docs.couchbase.com/sdk-api/couchbase-node-client/bucketmanager.js.html), it is not required. And I also tested is `ottoman.bucketManager.getAllBuckets()` and it looks ok to me
2. interface from node-sdk not exposed, `ottoman.d.ts` has something like this

```js
// this is an example, most of them returns any
/**
     * CollectionManager allows the management of collections within a Bucket.
     */
    get collectionManager(): any;
    /**
     * Gets a bucket manager for this cluster
     */
    get bucketManager(): any;
```

So when using, it doesn't provide the appropriate typings

![image](https://user-images.githubusercontent.com/37484538/108328566-ba3f9a00-7207-11eb-9f48-d7b6839b5a8b.png)

3. Not sure if I see wrongly, but the doc for [createCollection](https://docs.couchbase.com/sdk-api/couchbase-node-client/CollectionManager.html), where the option has [CollectionSpec](https://docs.couchbase.com/sdk-api/couchbase-node-client/global.html#CollectionSpec) also doesn't seem to match the [source](https://docs.couchbase.com/sdk-api/couchbase-node-client/collectionmanager.js.html). It does not seem to take in `maxExpiry` even if you specify in `CollectionSpec`
4. When dropping scope that does not exists, it simply throws `failed to drop scope`. Could it have better feedback, such as `scope exist`. I see in the API, it seem like it should throw `ScopeNotFound` error?
5. How do I use `ensureCollections` API? I tried to use something like this, but it doesn't seem to do anything. I tried to place before `start` method too

```js
const initOttoman = async (searchConsistency: SearchConsistency = SearchConsistency.NONE) => {
    ottoman = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection', searchConsistency });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password'
    });


    await ottoman.start();
    await ottoman.ensureCollections();
}
```

**Comment by AV25242** [comment]
_1 - node-sdk-api - getAllBuckets is not correct. Doc indicate the API requires to pass in bucketName but if you see the source, it is not required. And I also tested is ottoman.bucketManager.getAllBuckets() and it looks ok to me._
   
    That looks like a Node.js SDK API documentation concern. I will let the team know, thanks for brining it up. 
    
2 - interface from node-sdk not exposed, ottoman.d.ts has something like this

     In general we are aware of Node.js typescript generation issues, this will be handled in future ?(no ETA as such). Probably the one you are talking about has to do something with it.

3 -  Not sure if I see wrongly, but the doc for createCollection, where the option has CollectionSpec also doesn't seem to match the source. It does not seem to take in maxExpiry even if you specify in CollectionSpec
       
        Will take it to the Node Team. 
        
4 - When dropping scope that does not exists, it simply throws failed to drop scope. Could it have better feedback, such as scope exist. I see in the API, it seem like it should throw ScopeNotFound error?

        This should be fixed with https://github.com/couchbaselabs/node-ottoman/issues/393
        
5 - How do I use ensureCollections API? I tried to use something like this, but it doesn't seem to do anything. I tried to place before start method too

        You would not use ensureCollections with Start, instead you will use one of them.  start calls ensureCollections and ensureIndexes (encapsulates them).  If you want to just create scopes and collections you will call it and it should resolve the configuration settings to figure out what scope and collection names you want to create and will do so.

**Comment by bwgjoseph** [comment]
> If you want to just create scopes and collections you will call it and it should resolve the configuration settings to figure out what scope and collection names you want to create and will do so.

Does that mean it will create when it starts? or on-demand when the first document get created?

Similar to the example above,

```js
const initOttoman = async (searchConsistency: SearchConsistency = SearchConsistency.NONE) => {
    ottoman = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection', searchConsistency });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password'
    });


    await ottoman.start();
}
```

After I run this, I don't see `testDropScope` created.

![image](https://user-images.githubusercontent.com/37484538/109016306-03548a00-76f1-11eb-86b9-5c6761c73825.png)

Is that the expected behavior?

**Comment by AV25242** [comment]
@bwgjoseph  scopes and collections should be created at start.  You running against 7.0 ?  I dont have the full perspective of your code but what is initOttoman should that be initiOttoman.start() ?  We are using it quite often and have no complaints.
Can you share more code ?>

**Comment by bwgjoseph** [comment]
Do you have a sample code?

I'm doing this, but it doesn't seem to trigger a create too

```js
const initOttoman = async (searchConsistency: SearchConsistency = SearchConsistency.NONE) => {
    ottoman = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection1', searchConsistency });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password'
    });


    await ottoman.start();

    const testSchema = new Schema({ name: String });
    model('testModel', testSchema);
}

await initOttoman();
```

Not sure if I'm doing it wrong

**Comment by AV25242** [comment]
Hi @bwgjoseph 

`const { model, Schema, Ottoman } = require('ottoman')

const initOttoman = async () => {
    ottoman = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection1' });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'travel',
        username: 'Administrator',
        password: 'password'
    });

    const testSchema = new Schema({ name: String });
    model('testModel', testSchema);
    await ottoman.start();


}

initOttoman();`

Got the following results

```
Scope created:  testDropScope
collection created: testDropScope/testDropCollection1
```

Place ottoman.start towards the end.

![Screen Shot 2021-02-25 at 12 50 50 PM](https://user-images.githubusercontent.com/5351738/109202138-443bb580-7768-11eb-80b1-88d551cf2af9.jpg)

**Comment by bwgjoseph** [comment]
I actually did tried placing it after `start()`, and I just tried again and it still doesn't work for me. Not sure what am I missing.

How do I turn on the logs so I can see what's happening? Is `ottoman` using `debug` for logs?

**Comment by AV25242** [comment]
@bwgjoseph  can you try this



    const testSchema = new Schema({ name: String });
    ottoman.model('testModel', testSchema);
    await ottoman.start();


The change is fully qualifying model by adding the instance before it i.e ottoman.model instead of just model.

**Comment by bwgjoseph** [comment]
Thanks, I tested and it works.

Any particular reason for that? I imported the `model` from `ottoman` though.

So it has to be triggered from the connection that I'm in, in order to be able to issue the command correctly to manage the bucket? In that case, in all the docs especially in [model](https://v2.ottomanjs.com/guides/model.html#compiling-your-first-model), would that be also `ottoman.model` instead of `model`?

Also, I noticed that there's a number `console.log` in the codebase, which I think is not such a good idea. Since it logs directly onto my console.

![image](https://user-images.githubusercontent.com/37484538/109422875-43c94600-7a18-11eb-8aa8-9e54bb7b5d2b.png)

**Comment by gsi-alejandro** [comment]
Hi @bwgjoseph 

When an Ottoman application starts, the first Ottoman instance will be saved as the default instance, the start, model, connect are standalone functions that will use the default instance under the hood in order to keep the Ottoman use as simple as possible.
If you want to ensure each method over a specific instance you must use the notation instance.start, instance.model, instance.connect instead.
If you want to ensure the use of the default instance use only the standalone method start, model, connect.

but is not recommended mix them:

```
// this is not recommended
import { model, start, connect } from 'ottoman';

connect(...)

model('user', schema)
ottoman.start()
```

------------------------------------------

```
// recommended way for only 1 Ottoman instance
import { model, start, connect } from 'ottoman';

connect(...)

model('user', schema)
start()
```

-------------------------------------------

```
// recommended way for handle many instances
import { Ottoman } from 'ottoman';

const ottoman = new Ottoman()
const ottoman2 = new Ottoman()

ottoman2.model('user', schema)
ottoman2.start()
```

Note: the connect function will be able to create a default instance if it doesn't exist.

Notice: `model` is a method from Ottoman, not from Model -> this is the documentation https://v2.ottomanjs.com/guides/ottoman.html

I don't think the idea to log the creation of scopes and collections be wrong, they are useful logs even in a production environment. (info log level)
but we are discussing the following options to include in the next release:

1. - Only log this scopes and collection creation status message when debugging. (DEBUG=true)
2. - Remove logs.
3. - Keep login (Actual behavior)

I hope this help! Thank you.

**Comment by bwgjoseph** [comment]
@gsi-alejandro thanks for the detailed explanation! It's really helpful, and wish to further clarify some stuff

I've re-looked in the documentation, and based on my understanding, a default connection will be created if I use either 

1. connect(...)
2. new Ottoman(...)

And either way, calling `getDefaultConnection()` will return me the default connection instance. Am I right?

So assuming that my assumption is correct, then doing what I did in https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/4#issuecomment-785982781 should cause it to use the default connection to call the `model` method? Although, I agree with you that it should not be the recommended way. I thought that `ottoman` will know what is the default, that even if I have done the `not recommended way`, it should still work?

To clarify my point

```js
// this will be the instance if I get getDefaultConnection()
ottoman1 = new Ottoman({ scopeName: 'testDropScope', collectionName: 'testDropCollection1', searchConsistency });

// default
ottoman1.connect({
	connectionString: 'couchbase://localhost',
	bucketName: 'testBucket',
	username: 'user',
	password: 'password'
});

// default
await ottoman1.start();

const testSchema = new Schema({ name: String });
// getDefaultConnection() = ottoman1
// so calling model method, will make it run on the default connection instance? which is ottoman1
// so in theory (from my understanding from the docs), it should work even without ottoman1.model
model('testModel', testSchema);
```

These are all based on the documentation, which state in [default ottoman instance functions](https://v2.ottomanjs.com/guides/ottoman.html#using-the-default-ottoman-instance-functions), [default-ottoman-instance](https://v2.ottomanjs.com/guides/ottoman.html#default-ottoman-instance) and what you have explained

If my understanding is correct thus far, then not calling `ottoman1.model` should work as well, or it should throw an error and don't allow it to do so? Or the way how `defaultConnection` works needs to be re-defined or state more clearly in the documentation?

---

It is definitely a good idea to log out DEBUG, INFO, etc logs but hiding back flags and only output to my console when I explicitly say so. So in a number of libraries that I've worked with, they use [debug](https://www.npmjs.com/package/debug) so I can toggle it as and when I need to like such `DEBUG=ottoman` then the logs will be display and pipe to the console.

The way that is done in [mongoose](https://mongoosejs.com/docs/faq.html#enable_debugging) is like so `mongoose.set('debug', true)`

**Comment by gsi-alejandro** [comment]
Hi @bwgjoseph 

_Documentation will be updated replacing `getDefaultConnection` for `getDefaultInstance` in the example code._

Answers:
1. `getDefaultInstance` function will return the default instance or undefined if not created yet, no matter the way it was created (new Ottoman or connect(...))

2. Yes, it should work even if you mix instance methods (`ottoman1.start` and just `model`) if you only have 1 Ottoman's instance.
_Notice: Always define all your `models` before using the `start` function._

3. We are going to hide info logs when using DEBUG=true (nodejs environment in debugging mode standard way), also we are going to provide Ottoman a new configuration to start in DEBUG mode to achieve something like mongoose does `mongoose.set('debug', true)`.

**Comment by bwgjoseph** [comment]
Hi,

So I tested with `alpha.19` and different combination.

I'm still using this to initialize the connection

```js
const initOttoman = async (searchConsistency: SearchConsistency = SearchConsistency.NONE) => {
    ottoman = new Ottoman({ scopeName: 'testScope', collectionName: 'testCollection', searchConsistency });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password'
    });

    // see below for the different combination
}
```

```js
// c1 - working
const testSchema = new Schema({ name: String });
ottoman.model('testModel', testSchema);
await ottoman.start();

// c2 - not working
const testSchema = new Schema({ name: String });
model('testModel', testSchema);
await ottoman.start();
```

For `c2`, based on your explanation, it should work?

---

The behavior of mixing seems to be producing confusing result. Also, from the documentation, I would assume that it is not required for `models` to be defined before `start` and it might not be always possible to declare all `models` upfront before the start.

In my app, I have `post.model.ts`, `comment.model.ts` that declares the model only and I have a `ottoman.ts` that define the connection and connects it

```js
// post.model.ts
model('post', postSchema);

// comment.model.ts
model('comment', commentSchema);

// ottoman.ts
ottoman.connect({ .. })
await ottoman.start()

// app.ts
server.listen()
```

If the above is my use-case, then it wouldn't be obvious for me (for dev) to notice the mistake right away.

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

**About `c2`**
no, the `c2` couldn't works because:
`model('testModel', testSchema);` will register testModel to the default instance for sure

and 
`await ottoman.start();` will execute the `start` function in the ottoman instance that could be or not the default instance.


To make sure the `c2` works replace it with the below code:
```
// c2 - will work
const testSchema = new Schema({ name: String });
model('testModel', testSchema);
await start();
```
this way you are ensuring that `model` and `start` will be executed in the same instance.

**About `start` documentation**
I agree about lacking documentation for the `start` function, we'll try to add a section to explain it ASAP.
Basically, the `start` function does:
- Create scopes/collections for the register models. (If needed)
- Create the indexes defined in the register models.



**About multiples instances**

If you want to ensure you only have 1 Ottoman instance you can use this `initOttoman` function. You will need this validation because this function is executed many times.
```
const initOttoman = async () => {
    let ottoman = getDefaultInstance();
    if (!ottoman) {
        ottoman = new Ottoman({ collectionName: '_default' });
    }

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'travel-sample',
        username: 'Administrator',
        password: 'password'
    });
  }
```

Alternatively, if you want multiples instances you can return the ottoman instance and used it in your tests
```
const initOttoman = async () => {
 
    const ottoman = new Ottoman({ collectionName: '_default' });

    ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'travel-sample',
        username: 'Administrator',
        password: 'password'
    });

   return ottoman;
  }
```

example test file...
```
describe('test model options', async () => {
    before(async () => {
        await initOttoman(SearchConsistency.LOCAL);
    });

describe('test model options', async () => {
    let ottoman: Ottoman;
    before(async () => {
        ottoman = await initOttoman(SearchConsistency.LOCAL);
    });

    it('ottoman - change idKey', async () => {
        assert.strictEqual(ottoman.config.searchConsistency, SearchConsistency.LOCAL);
 ....
```

**About common app use-case**

You can check our examples maybe it helps:
https://github.com/couchbaselabs/try-ottoman-ts
https://github.com/couchbaselabs/try-ottoman

**Comment by gsi-alejandro** [comment]
@bwgjoseph 
I share with you how we configure our test environment:

This is the configuration file used to run the test in the Ottoman repo:
https://github.com/couchbaselabs/node-ottoman/blob/master/__test__/jest.setup.ts

1. We are creating an Ottoman's instance `beforeEach` test and connecting it to the Couchbase Server
2. `afterEach` we disconnect from Couchbase Server and remove the Ottoman's instance (using the `close` function)

Note: the `start` function is added inside the tests if needed. (always after defining the models).

I assume that mocha can do something like this, but I can't help because I never use mocha before.

**Comment by AV25242** [comment]
```
console.log(getDefaultInstance().models)
console.log(ottoman.models)
console.log(getOttomanInstances())
```

**Comment by gsi-alejandro** [comment]
@josephstgh 

I tested the `c2` case in a clean environment to make sure it works as expected.
Screenshot
![image](https://user-images.githubusercontent.com/15661442/114744772-098fdb80-9d1c-11eb-9ab2-c7d4bbc5e8da.png)

this is the code

i```
mport {connect, model, Ottoman, SearchConsistency, start} from "ottoman";

const ottoman = new Ottoman({collectionName: '_default'})

connect({
    connectionString: 'couchbase://127.0.0.1',
    bucketName: 'travel-sample',
    username: 'Administrator',
    password: 'password'
});

const User = model('User', { name: String });

const runLogic = async () => {
    await ottoman.start();

    const john = new User({name: 'Jhon'});
    await john.save();

    const userQuery = await User.find({}, {consistency: SearchConsistency.LOCAL})
    console.log(userQuery.rows)
}


runLogic();
```

I hope this can help you a little bit.

**Comment by bwgjoseph** [comment]
Hey @gsi-alejandro, 

Thanks for the input, appreciate it!

Will take a look at this issue slightly later...
