### ISSUE TITLE
replace operator

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#42]
Hi,

Take a look at this test case,

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/af026cb63150474c6af2ca29f8b2803e6d4d7505/test/ts/replace.test.ts#L69-L97

![image](https://user-images.githubusercontent.com/37484538/104837223-13a56800-58ee-11eb-869f-4c6f860dacb4.png)

Gist is that when I tried to use `replace` operator and specify a `non-existence` id, it seem to be creating new doc instead of throwing error like `document not found`. Seem like it's performing a `upsert` of sort

**Comment by AV25242** [comment]
@bwgjoseph  team is investigating it.

**Comment by AV25242** [comment]
This is a bug, will be fixed with next release 

https://github.com/couchbaselabs/node-ottoman/issues/364

**Comment by AV25242** [comment]
fixed with alpha.14 can you please review ?
