### ISSUE TITLE
support for schema add

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#46]
Hi,

Does ottoman allow to add field using the schema? see https://mongoosejs.com/docs/api.html#schema_Schema-add

Reason for this is that I have a global plugin that allows me to define to add a field that applies to all schemas

Thanks

**Comment by gsi-chao** [comment]
@bwgjoseph 
Currently it is not a functionality that we support, but we could add it to the roadmap

**Comment by bwgjoseph** [comment]
Thank you

**Comment by AV25242** [comment]
@bwgjoseph  trying to understand this request with my understanding and correct me if I am not right here.
So add basically gives the ability to extend an existing schema definition. If I were to relate this to OO Concepts, it would be more or like Inheritance, object A extends object B 

The idea is to define a global Schema and then using the add method extend any individual schema to add the behaviors defined in the global schema - am I close ?

**Comment by bwgjoseph** [comment]
I guess you're right. I think I'm using it something along this line

```js
// define the plugin in myplugin.js
const myPlugin = () => {
	schema.add({
		id: string,
		default: () => myIdGenerator()
	})
}

// in mongoose.js
import mongoose from 'mongoose'
import myplugin from 'myplugin.js'

const schema1 = new Schema({ fieldA: string });
const schema2 = new Schema({ fieldB: string });

mongoose.plugin(myplugin);

// this result in both schema1 and schema2 to have id field
```

```js
// in oop
class 2D { x: int, y: int } // x, y

class 3D extends 2D { z: int } // x, y, z
```

**Comment by AV25242** [comment]
got it ! 

I have created an issue https://github.com/couchbaselabs/node-ottoman/issues/384

**Comment by bwgjoseph** [comment]
I actually have another use case, which is almost similar but isn't provided by `mongoose` as well.

It's to actually extending the `schema` rather than using the `add` function. You can take a look at [mongoose-extend-schema](https://www.npmjs.com/package/mongoose-extend-schema) which is a 3rd party lib but essential does what you mentioned in terms of OOP.

In a way, I could have a `baseSchema` and other schema extends the `baseSchema` and add on

```js
const baseSchema = new Schema({ id: string, somecommonfield: string });

// has id, somecommonfield, aField, bField
const aSchema = extendSchema(baseSchema, { aField: number, bField: boolean });

// has id, somecommonfield, bField, cField
const bSchema = extendSchema(baseSchema, { bField: number, cField: Mixed });
```

Functionally, it should be both work the same (I think). I probably prefer this over the `.add`. For your consideration.

**Comment by httpJunkie** [comment]
This feature has been added through the PR in the following ticket: 
https://github.com/couchbaselabs/node-ottoman/issues/384

We can achieve this particular use case using: 

```
const baseSchema = new Schema({ id: string, somecommonfield: string });
const aSchema = new Schema()

aSchema.add(baseSchema).add({ bField: number, cField: Mixed })
```

**Comment by bwgjoseph** [comment]
Thank you! Will test it once the newer alpha is release

**Comment by AV25242** [comment]
@bwgjoseph  alpha 18 was released yesterday
