### ISSUE TITLE
Any way to define global idKey

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#48]
Hi,

In [modelOptions](https://v2.ottomanjs.com/guides/model.html#model-options), I can define the `idKey` per model, but is there any way to define it in global option? So that I don't have to define per model.

This would be useful since `idKey` usually don't change per model, and is same across all models

Thanks

**Comment by AV25242** [comment]
@bwgjoseph  interesting that you say that idKey doesn't change per model, I am in the opinion that idKey may overlap but as a general usage idKey would be a concern to its unique model.

**Comment by bwgjoseph** [comment]
Hmm. My assumption is that `idKey` is similar to the "primary key field" of the model?

Currently, all models are default to `id` and in that sense, I want to change the default `id` to `kId` for example.

Of course, if i can also change the `idKey` using the model options again if I want to.

**Comment by AV25242** [comment]
Your assumption is absolutely correct @bwgjoseph and you and I are talking the same thing.  Its like a PK for a table in relational world, in a more general sense PK will be different for different tables. I understand sometimes you may call it Id (like in your use case) but if you were to think in general PK names could end up being like CustomerId or EmployeeId or sometime it may not be a candidate key but a combination of keys (which by the way I have a ticket open to get that accommodated) .

**Comment by bwgjoseph** [comment]
When I mentioned that the `idKey` don't change, I was relating more towards `mongo`, and `couchbase`. By default, when I don't specify any `idKey`, the default one will always be `id` for all collections. And in `mongo`, the default will always be `_id`, for all collections. 

To further illustrate the point, this is what it is when creating a document using `mongoose` and `ottoman`

```js
// mongoose, note _id is the "primary key" fieldname
{
    capacity: 250,
    _id: 60215234c735710a5cf53bf9,
    callsign: 'Hawk',
    name: 'Couchbase Airlines',
    scheduledAt: 2020-11-20T03:30:00.000Z,
    model: 'A380',
    size: 'S',
    __v: 0
  }

// ottoman, note id is the "primary key" fieldname
rows: [
    _Model {
      _type: 'Airplane',
      id: '7a00c3b7-60c7-49db-9da0-1cb318f333c2',
      name: 'Couchbase Airlines',
      operational: true,
      scheduledAt: 2020-11-20T03:30:00.000Z,
      size: 'S'
    }
  ]
```

But if I were to change the `idKey` like such

```js
ottoman.model('opts', schema, { idKey: '_id' });

// the "primary key" fieldname is now _id instead of id
_Model {
      _id: 'b5071155-172a-49aa-97f1-9669b5aa78dc',
      _type: 'opts',
      name: 'hello',
      operational: true
    }

// another example
ottoman.model('opts', schema, { idKey: 'mycustomidfield' });

_Model {
      _type: 'opts',
      mycustomidfield: 'b98af84b-d4ef-47c0-a467-d5e45f3ae764',
      name: 'hello',
      operational: true
    }
```

I haven't been working with SQL for quite a long time, but IIRC, you could just set the PK in any field, by defining the constraint. So in that case, yes, if the table columns name are defined as `customerId` or `employeeId` then those can be a PK. If you are talking about this issue that you created - https://github.com/couchbaselabs/node-ottoman/issues/377, I'm not sure how is that related to `idKey` in the `ModelOptions`

My understanding based on the API, is to change the default fieldname of the "id" field. Let me know if I'm misunderstanding any of these.

**Comment by AV25242** [comment]
No I think you and I are talking about the same thing. I was trying to understand the usecase which I now understand well enough. This is very useful for those who are migrating from mongodb, which would by default use _id as a key and you dont want to basically let all models know that _id is your primary key rather define it in one place, makes sense to me. 

Added issues https://github.com/couchbaselabs/node-ottoman/issues/401

**Comment by bwgjoseph** [comment]
Yup, that's correct.

Thanks!

**Comment by httpJunkie** [comment]
Solved with this PR: https://github.com/couchbaselabs/node-ottoman/pull/403/files

**Comment by bwgjoseph** [comment]
Thank you! Will test with the newer alpha release

**Comment by AV25242** [comment]
@bwgjoseph alpha 18 was released yesterday. Can you please try out

**Comment by bwgjoseph** [comment]
Thank you, didn't realize that as the codebase didn't have the changes. Will test it out soon
