### ISSUE TITLE
API to remove multi docs

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#5]
In `mongoose`, I have [remove](https://mongoosejs.com/docs/api.html#model_Model.remove), [deleteOne](https://mongoosejs.com/docs/api.html#query_Query-deleteOne), [deleteMany](https://mongoosejs.com/docs/api.html#query_Query-deleteMany) to remove one or more document at one go. How can I do the same in `Otterman`? In the docs, I only see one sample which is using [remove](https://v2.ottomanjs.com/classes/document.html#remove)

**Comment by bwgjoseph** [comment]
@AV25242 replied

Remove is the only Key Value operation supported via Ottoman, however if you want to do more operations you can use its powerful N1QL feature and write N1QL queries which Mongoose doesnt have.

**Comment by bwgjoseph** [comment]
I understand that `N1QL` allow us to write much more powerful queries, which personally, I feel that it is something like [aggregation-pipeline](https://docs.mongodb.com/manual/core/aggregation-pipeline/) from `mongodb` that allows us to write more complex query. I'm not saying that both providing the same feature, but something like it's a platform/tool to allow developer to do more complex stuff if required.

IMHO, I find that CRUD operations (including multi operations) should be provided by `Ottoman` to developers so that we don't have to dive deeper into `N1QL/Query Builder` just to perform multi update/delete operations.

I hope that this could be considered since `Ottoman` is about providing abstraction and do all the heavy lifting for developers

Thanks!

**Comment by AV25242** [comment]
remove and deleteMany they are functionally the same  what is the level of difference you were looking here ?
deleteOne what is specific usecase ?

**Comment by bwgjoseph** [comment]
I was quoting the different methods from `mongoose` but we are currently using `deleteOne` to delete one item by passing in the `id` filter and `deleteMany` to pass in `filter` to delete any item that matches the filter.

Taking the example from `mongoose`:

```
await Character.deleteOne({ _id: '12345' });
await Character.deleteMany({ name: /Stark/, age: { $gte: 18 } });
```

**Comment by AV25242** [comment]
On the DeleteOne I would rather prefer it to be DeleteById, if you want to  delete one you can use the remove method. I think DeleteById makes more sense and makes it more cleaner.

**Comment by AV25242** [comment]
Lets discuss it next week

**Comment by bwgjoseph** [comment]
Is there any existing examples to delete docs using `Query Builder`?

**Comment by bwgjoseph** [comment]
As a note, there should have a way to `updateMany` as well

**Comment by bwgjoseph** [comment]
@AV25242,

I see that `Key-Value Operations` in the docs is `remove`, but in the issues you created in `node-ottoman` was `deleteById` and `deleteMany`. I thought it should be `removeById` and `removeMany`.

**Comment by AV25242** [comment]
> @AV25242,
> 
> I see that `Key-Value Operations` in the docs is `remove`, but in the issues you created in `node-ottoman` was `deleteById` and `deleteMany`. I thought it should be `removeById` and `removeMany`.

Correct, so remove is essentially removeById i.e you can pass in a Key and remove a document. Internally it uses KV op collection.remove(key), so essentially I have create a duplicate ticket for deleteById, which I will remove.

deleteMany - Will be a N1QL wrapper, so we would keep it that way

**Comment by bwgjoseph** [comment]
> Internally it uses KV op collection.remove(key), so essentially I have create a duplicate ticket for deleteById, which I will remove.

Yup, agreed.

> deleteMany - Will be a N1QL wrapper, so we would keep it that way

Sorry, I don't quite follow. That would mean that `ottoman` will still expose a `removeMany` method where internally it construct the n1ql?

**Comment by AV25242** [comment]
@bwgjoseph thats still being discussed but yeah it would be deleteMany using n1ql

**Comment by AV25242** [comment]
Tickets have been created to address 

    rename remove to removeById as its a KV operation 
    add remove functionality that accepts a filter

**Comment by AV25242** [comment]
RemoveById is taken care of with ticket  -https://github.com/couchbaselabs/node-ottoman/issues/305

RemoveMany - https://github.com/couchbaselabs/node-ottoman/issues/304

**Comment by bwgjoseph** [comment]
Hi,

While verifying this, there's seem to have some minor issue.

Why is it that when the filter does not match, it throws an `document not found` exception?

```js
// assuming I have a couple of existing docs in db and none matches

await Airplane.removeMany({
	name: 'should not find any'
},
{
	consistency: SearchConsistency.LOCAL
});
```

```js
1) test removeMany function
   ottoman - should NOT remove many docs (does not match):
 Error: document not found
  at Z:\mongoose-vs-ottoman\node_modules\ottoman\src\model\create-model.ts:226:15
  at Generator.next (<anonymous>)
  at fulfilled (node_modules\ottoman\lib\model\create-model.js:5:58)
```

You can also look at [ottoman - should NOT remove many docs (does not match) test](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/removeMany.test.ts)

And if I'm not mistaken, this happens on other APIs where you pass in `filters` as well. It shouldn't throw an exception when it doesn't find any docs.

**Comment by AV25242** [comment]
@bwgjoseph  will get back

**Comment by bwgjoseph** [comment]
I would also like to ask on the behavior when using `multi` operations and what happens when one of the item fails, does it stop or continue the operations.

```js
// assume doc2 is a invalidate doc that does not match the schema
createMany([doc1, doc2, doc3, doc4]);
// not sure if applicable to updateMany and removeMany
```

Would the behavior be:

1. create doc1, fail to insert doc2, create doc3 and then doc4
2. create doc1, fail on 2, stop the rest of the operation

I think the documentation also doesn't explain this, and I think might be a good idea to include it in

**Comment by AV25242** [comment]
In Bulk Operations the behavior should be

act on all documents regardless of success or failure and return back the result that tells you the success count and failure id/message.
right now it should do that (with an exception of message which I have already created a ticket for)
hope this help !
