### ISSUE TITLE
registerGlobalPlugin not exposed

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#50]
Hi,

I am trying out [global-plugin](https://v2.ottomanjs.com/guides/schema.html#global-plugins) but following the example does not work

![image](https://user-images.githubusercontent.com/37484538/108320370-af800780-71fd-11eb-9a61-809d56cf5b93.png)

**Comment by AV25242** [comment]
Will get back to you on this, you seem to be right.

**Comment by bwgjoseph** [comment]
LGTM

**Comment by bwgjoseph** [comment]
Re-opening this

1. How do you register a global plugin per connection? 

2. Also, during my test, when I declare `registerGlobalPlugin` to register my plugin twice of the same type (e.g `schema.pre('save')`), it ignores the 2nd one and just register for the first. What is the registration priority? Only take in the first one that has been registered? or the latest win? In this case, I think it is the first one win, but maybe can describe in the documentation how it works?

**Comment by gsi-chao** [comment]
Hello @bwgjoseph 
1- How do you register a global plugin per connection?
Currently, the register global plugin feature only works globally.
2- Can you share with me the specific test?, because I reproduce your test case, and all works like expected

**Comment by gsi-chao** [comment]
test('Apply global plugin', async () => {
      let log1 = false;
      let log2 = false;
      const logPluginPre1 = (schema) =>
        schema.pre('save', () => {
          log1 = true;
        });
      const logPluginPre2 = (schema) =>
        schema.pre('save', () => {
          log2 = true;
        });
      registerGlobalPlugin(...[logPluginPre1, logPluginPre2]);
      const userSchema = new Schema({ name: String });
      const User = model('User', userSchema);
      const user = new User({ name: 'John' });
      await user.save();
      await delay(1000);
      await user.remove();
      expect(log1).toEqual(true);
      expect(log2).toEqual(true);
    });

**Comment by bwgjoseph** [comment]
Hi,

As I won't be near my machine for the next couple of days, I can't give you any specific example for now. Let me get back to you again.

1. I apologize if I wasn't very clear. I meant can I register global plugin per ottoman connection.

```
Const o1 = new ottoman()
Const o2 = new ottoman()
```

Can I register the global plugin and only make it available for o1 but not o2 and vice versa. Or I could also want to make it available to both o1 and o2.

Is it possible?

2. My example wasn't too clear as well. I have 2 connection like the example I have given above and I registered for .pre(save) as the global plugin and the 2nd one doesn't seem to do anything. 

I have to get back to you again with more concrete test cases.

Thanks.

**Comment by bwgjoseph** [comment]
You can find the example in https://github.com/bwgjoseph/mongoose-vs-ottoman/commit/832524543fc0449cc67b7ae9fa088cd8aa8581c9

Do update `package.json` - `test` script to `mocha --require ts-node/register test/ts/registerGlobalPlugin.test.ts --exit` so that it only runs that particular test

I managed to reproduce the issue even with a single connection but registering both plugins. Not sure if it's because I'm doing something wrong.

This is the output

![image](https://user-images.githubusercontent.com/37484538/114574736-1543b980-9cac-11eb-8134-9748651884cf.png)

I also tried to register as such

```js
registerGlobalPlugin(pluginLog);
registerGlobalPlugin(pluginLog2);
```

But nothing change
