### ISSUE TITLE
flaky test when running multiple test case (updateById, updateMany)

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#51]
Hi,

I'm trying to run against a number of test case at once, to ensure that all test passes (no test case conflict). So after running a number of testes, I had couple of test that is flaky (in `updateMany` test suite). After a number of trial and error, I think I managed to pinpoint down to two conflicting test case to replicate it, but you probably have to run a couple of times to get the error too.

The test case are 

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/5f9d525dbde26518ad1659977158a6fc4d18f842/test/ts/updateById.test.ts#L39

And the following is the failed one

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/5f9d525dbde26518ad1659977158a6fc4d18f842/test/ts/updateMany.test.ts#L38-L76

So the test failed where it states something along this line

```js
{
 "message": {
   "errors": []
-    "match_number": 3
-    "success": 3
+    "match_number": 2
+    "success": 2
 }
 "status": "SUCCESS"
}
```

If you take a look at the test case, I only created 2 items but why would the error throw back with 3 items?

So in order to figure out which is the offending test case, I used the post save hook to print out the id so I can figure out which test case this extra item comes from.

```js
ottomanAirplaneSchema.post('save', (doc) => console.log(doc.id));
```

And, in my `updateMany` test case, I added 

```js
before(async () => {
        await removeDocuments();
        const Airplane = getOttomanModel();
        console.log('aa', await Airplane.find());
    });
```

to ensure that all documents are cleared, and none should still be there. However, when the test did fail, it does print out some existing data even when I explicitly tried to cleared it.

```js
aa {
  meta: {
    requestId: '354244b4-26ec-489a-8f39-795adcdbe2e9',
    clientContextId: '29fedae71cef1793',
    status: 'success',
    signature: { '*': '*' },
    profile: undefined,
    metrics: {
      elapsedTime: 2.5418,
      executionTime: 2.4783,
      sortCount: undefined,
      resultCount: 1,
      resultSize: 412,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: [
    _Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      capacity: 250,
      destination: [Array],
      extension: 'abc',
      // this comes from updateById test case but appearing in updateMany test case which shouldn't be
      id: '47da43f4-b16a-4891-ac6e-95a8dcd7b31c',
      info: [Object],
      location: [Object],
      model: 'A380',
      name: 'Couchbase Airlines',
      operational: true,
      scheduledAt: 2020-11-20T03:30:00.000Z,
      size: 'S'
    }
  ]
}
``` 

Where this `47da43f4-b16a-4891-ac6e-95a8dcd7b31c` comes from `updateById` test case.

---

I suspect that this might have something to do with `Consistency` but I'm not quite sure how, and what is exactly causing my issue. `createMany` and `removeMany` doesn't seem to have flaky test from the many trial runs so far.

Let me know if there is more information I can provide to help.

Thanks

**Comment by gsi-chao** [comment]
Give me time to reproduce the exact problem and get back to you.

**Comment by gsi-chao** [comment]
Hello @bwgjoseph, I try to mount your environment but I have 2 problems.
1- When I create a docker container and run the npm test. I found this issue. "No index available on keyspace `default`:`testBucket` that matches your query".  You need to add to the setup_couchbase.sh the creation of a bucket index using this N1QL. 
`CREATE PRIMARY INDEX ON `default`:`testBucket``
2- After solving this problem I went back to using npm test. In this case, I see that the tests are not running, only this test is executed.
![image](https://user-images.githubusercontent.com/32143683/110139917-8df85180-7da1-11eb-8424-13ffd51664b0.png)
How do you normally run the tests?

**Comment by bwgjoseph** [comment]
Hi @gsi-chao,

Will take note of number 1.

As for the second issue, do add `.only` to the 2 test case (and remove any other that has `.only`) that I mentioned in the first post, and it should run only

```
ottoman - should NOT update doc when id does not match
ottoman - changing all docs with "Couchbase" in the name field, size to M
```

**Comment by gsi-chao** [comment]
Thanks, I will back to you soon.

**Comment by gsi-chao** [comment]
I run the updateMany and the updateById test and all works like a charm
![image](https://user-images.githubusercontent.com/32143683/110144307-30b2cf00-7da6-11eb-98f0-c0ab9a8c54fa.png)

**Comment by bwgjoseph** [comment]
Can you run only that 2 particular test case, and you may need to run a couple of times to hit the problem?

This is what I have before the start of the test

![image](https://user-images.githubusercontent.com/37484538/110145178-1d3e4d00-7e14-11eb-90be-6a62a0d60b45.png)

And this is what I get after running the test

![image](https://user-images.githubusercontent.com/37484538/110145386-55de2680-7e14-11eb-8b6c-3b4742d89dc3.png)

So if you see the test case in `updateMany`, I have set a `before` hook to remove all documents before the start of the test. So by right, before `updateMany` test case is supposed to run, it will remove all documents. And my test case in `removeMany` only create 2 document.

I'm puzzled as to why the document from the previous test case is not being removed. All other test case doesn't seem to face the same issue, as of now, it seem that only these are being affected.

Any way for me to verify anything or look out for?

**Comment by gsi-chao** [comment]
🎉 I found the error. Look at this declaration of mocha documentation.
```
describe('hooks', function() {
  before(function() {
    // runs once before the first test in this block
  });

  after(function() {
    // runs once after the last test in this block
  });

  beforeEach(function() {
    // runs before each test in this block
  });

  afterEach(function() {
    // runs after each test in this block
  });

  // test cases
});
```
The before hook "runs once before the first test in this block" in both case the test not appear first, so the before hook only run for the first test. You need to change the before hook to beforeEach and all will works fine.

![image](https://user-images.githubusercontent.com/32143683/110147966-3f9b8080-7daa-11eb-8030-810837510c6f.png)
With before hook

![image](https://user-images.githubusercontent.com/32143683/110148067-5e017c00-7daa-11eb-965d-b257e9445279.png)
With beforeEach hook

**Comment by bwgjoseph** [comment]
That's my understanding of the mocha hooks. So I have 2 describe block (updateById, updateMany), so it will run `before` once for each test suite. Does the order of the test in each test suite matters?

Anyhow, I removed all other test cases except for the 2 in each of the test case, and continue to use `before` hook. I tried running it over a few (6-8) times, and it is still flaky where it sometimes pass, and sometimes fails. Then I changed to use `beforeEach` and it continues to be flaky. So you might want to try running the test a couple of times?

**Comment by gsi-chao** [comment]
You are right, I ran it 2 times and it didn't give me the error, now I do it again and it happens. I will have to review more thoroughly. I don't think it's an issue on couchbase. I think it is something more related to mocha.

**Comment by bwgjoseph** [comment]
I agree with you, it does seem like it could be mocha issue but when I ran over all the test cases, only these 2 test cases gave me this issue. So if this is really mocha issue, then it probably shouldn't happen only for these test cases also. Hence, I'm still quite confused with the exact cause.

If you could help to isolate the issue (verifying not ottoman issue), maybe we can report the issue to mocha. In my existing projects, I have been using mocha with `before`, `beforeEach` hooks but I have not seen this kind of flaky issue before though.

Thanks for helping out! Appreciate it

**Comment by gsi-chao** [comment]
I am trying to make sense of what is happening, I do not want to totally rule out couchbase as the problem, since there is a refreshing time of the indexes after each operation is executed. Maybe it could be something along these lines. I'm going to check a little more.

**Comment by bwgjoseph** [comment]
Yup, agreed. As I also mentioned in the first post, whether there is something to do with the `consistency` or something along that line... 

Ping me if you require me to test anything out.

**Comment by gsi-chao** [comment]
I create a delay function to try to simulate a refresh index time.
```
export const delay = (timems: number) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, timems);
  });
```

And update the removeDocument method
```
const removeDocuments = async () => {
    const query = 'DELETE FROM `testBucket`';
    try {
        await getDefaultInstance().query(query);
        await delay(500);
    } catch (err) {
        console.log(err);
        throw err;
    }
}
```

After this change, everything runs correctly. I come to the conclusion that the problem could be about the indexes and therefore the search consistency could be the solution.

I'm going to review the implementation of the Search Consistency in ottoman, if I don't see anything unusual I think we should pass this on to the couchbase sdk team.

**Comment by bwgjoseph** [comment]
Great! Keep me posted with any updates, thanks!

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

please update your `removeDocuments` function with this one and everything should work as expected.

```
const removeDocuments = async () => {
    const query = `
    DELETE FROM \`travel-sample\`
    `
    try {
        await getDefaultInstance().bucket.query(query, { scanConsistency: "request_plus" });
    } catch (err) {
        console.log(err);
        throw err;
    }
}
```

**Comment by bwgjoseph** [comment]
Hi @gsi-alejandro,

I changed to what you've told me but it throws me `not a function error`.

![image](https://user-images.githubusercontent.com/37484538/115101270-270bb200-9f75-11eb-9986-411e5e0de904.png)

![image](https://user-images.githubusercontent.com/37484538/115101280-40146300-9f75-11eb-8a7e-3df04d34cdb7.png)

**Comment by gsi-alejandro** [comment]
@bwgjoseph sorry I was wrong, please use `cluster` instead of `bucket`:

 `await getDefaultInstance().cluster.query(query, { scanConsistency: "request_plus" });`

**Comment by bwgjoseph** [comment]
Thanks @gsi-alejandro, it works now!
