### ISSUE TITLE
support for case insensitive query

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#54]
Hi,

I don't think this is being supported right now, but do correct me if I'm wrong.

```js
// current data
{
  name: 'Joseph'
}

// case insensitive find
const find = Model.find({ name: 'joseph' });
```

This should return the data

**Comment by AV25242** [comment]
that is correct and I have created an issue https://github.com/couchbaselabs/node-ottoman/issues/422

**Comment by AV25242** [comment]
Checkout the new alpha.21 release and let us know.

**Comment by bwgjoseph** [comment]
I have tested this new option and have some feedback on this

1. Seem like the way to use it is to use together with `$eq` operator

```js
.find(
    { name: { $eq: 'couchbase airlines', $ignoreCase: true }},
    { consistency: SearchConsistency.LOCAL },
);

// I tried, it doesn't work
.find(
    { name: 'couchbase airlines', $ignoreCase: true }},
    { consistency: SearchConsistency.LOCAL },
);
```

It seem like it does support some operator but not `$ignoreCase`

![image](https://user-images.githubusercontent.com/37484538/113478645-b6688e00-94bc-11eb-8446-371e9d23c3af.png)

And it is quite confusing when I should use which pattern (for the filters), is there any document to explain this? Did I miss this in the documentation?

2. Is there a way to run the `$ignoreCase` per query rather than per field? This allows me to pass `$ignoreCase` to the options portion of the query rather than per field

```js
.find(
    { name: 'couchbase airlines' },
    { consistency: SearchConsistency.LOCAL, $ignoreCase: true },
);
```

**Comment by AV25242** [comment]
1 ) The documentation for $ignoreCase is in here https://v2.ottomanjs.com/guides/query-builder.html#build-a-query-by-using-parameters 
There should be test case around it as well.

2) Right now its at field level there is no  outer-level options.

**Comment by bwgjoseph** [comment]
What I meant was,

```js
// when do I use
// option 1
.find({ name: 'xyz', $someoperator })

// vs
// option 2
.find({ name: { $eq: 'xyz', $someoperator })
```

By `$someoperator`, I mean like like `$ignoreCase`, `$isNotNull` or any others supported operator

Because as you can see from the screenshot above, some operators are available to use when using `option 1`. How do I differentiate when do I use one over another? The documentation you pointed, just show a list of the possible operator but doesn't tell me when I should use which format (option 1/2). I'm not sure is it because I am missing something obvious here.

I hope you can consider supporting `$ignoreCase` at the outer level options (per query) as I have mentioned above. Thanks

**Comment by AV25242** [comment]
I have created an issue https://github.com/couchbaselabs/node-ottoman/issues/438 for Documentation.

For IgnoreCase on FindOptions lets  I have created an issue https://github.com/couchbaselabs/node-ottoman/issues/437

**Comment by bwgjoseph** [comment]
Thanks for creating the issues.

Just to be more explicit in my use case. Since $ignoreCase is to be supported in the options then this should work as well

```
.find({ name: 'joseph' }, { $ignoreCase: true A})
```

The difference is that not required to put $eq in the name portion in order for it to work

Thanks

**Comment by AV25242** [comment]
Should be available in next release

**Comment by AV25242** [comment]
Please check out alpha.22
