### ISSUE TITLE
discrepancy between findById and findOne returns

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#56]
Hi,

When using `findById` and if the document does not exist, it (by right) throws a `DocumentNotFoundError: document not found` (see #55) 

However, when using `findOne`, the documentation says that (and it does) return as `null` when the document is not found (see [findOne](https://v2.ottomanjs.com/classes/model.html#static-findone))

I have yet to test for the other `find*` methods.

Is it intentional for it to return differently, or should it be consistent in the response across all the `find*` methods?

---

Update: `findOneAndUpdate` also throws `document not found` error when unable to match the fitler

**Comment by AV25242** [comment]
should be fixed in the next release

**Comment by AV25242** [comment]
Please check out alpha.22

**Comment by bwgjoseph** [comment]
Have verified that `findOne` returns is consistent with the others but the docs has yet to be updated and is currently still reflecting as returning `null`

**Comment by AV25242** [comment]
let me check with the team @bwgjoseph

**Comment by bwgjoseph** [comment]
Just saw that the doc is not updated

See https://v2.ottomanjs.com/guides/model.html#querying

```js
User.findOne({ name: 'Jane' });
// will return a document with a User with the name "Jane" or null in case of not finding it
```

Doesn't match with code

![image](https://user-images.githubusercontent.com/37484538/117471062-0938d800-af8a-11eb-9591-9223c3752155.png)

**Comment by AV25242** [comment]
@bwgjoseph correct me if I have mistaken, but this ticket awaits only doc updates at the moment ? if thats true then can you move the issue under doc ticket we have please? and close this ticket.
If otherwise please let me know

**Comment by bwgjoseph** [comment]
That's correct.
