### ISSUE TITLE
support for schema.paths

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#58]
Hi,

Is there any way to grab the list of fields that is registered for a given schema?

```js
const myschema = new Schema({ name: string, capacity: number });

// get a list of schemas keys
// output [name, capacity]
Object.keys(myschema.paths);
// myschema.paths actually give the schema definition
```

I saw on the [docs](https://v2.ottomanjs.com/classes/schema.html#path) that `ottoman` has `path` but not `paths` method.

**Comment by AV25242** [comment]
I am not aware of something like this, but what would be the use case ?

**Comment by bwgjoseph** [comment]
I could say, write a plugin that only runs if a certain field exists.

```js
if (Object.keys(schema.paths).includes('certainfield')) {
   // do some manipulation to the data
}
```

or just purely check if certain fields exists

```js
function doesFieldExist(schema, fieldName) {
  return Object.keys(schema.paths).includes(fieldName);
}
```

I am currently using this checks to perform certain action across different schemas based on what fields exists or not exists.

**Comment by AV25242** [comment]
Lino will explore the [fields](https://v2.ottomanjs.com/classes/schema.html#fields) method on Schema

**Comment by AV25242** [comment]
from Lino

```
function doesFieldExist(schema: Schema, fieldName: string): boolean {
  return !!!schema.path(fieldName)
}
```

**Comment by bwgjoseph** [comment]
Thank you for the suggestion, it works as expected
