### ISSUE TITLE
expose node-sdk Manager interface

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#61]
From https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/4#issuecomment-781194208 Point 2

Expose `CollectionManager, BucketManager, etc` interface from `ottoman` (when possible)

**Comment by AV25242** [comment]
@bwgjoseph  mostly done after Node 3.2 release post June. But we will keep this to keep a tab at it.

**Comment by bwgjoseph** [comment]
Seem like the interface are defined now
