### ISSUE TITLE
expose ModelTypes

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#62]
Hi,

Currently, I need to use the types `ModelTypes` but it does not seem to be exported from the main typings.

I am currently importing via

```js
import { ModelTypes } from 'ottoman/lib/types/model/model.types';
```

instead of 

```js
import { ModelTypes } from 'ottoman';
```

Thanks

**Comment by AV25242** [comment]
**Available with aplha.28**

**Comment by bwgjoseph** [comment]
Verified working in alpha.28
