### ISSUE TITLE
id field

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#63]
Hi,

Can I verify that `ottoman/couchbase` only supports `string` as the `id`? Meaning to say that I cannot have `number` as my `id`

Thanks

**Comment by AV25242** [comment]
Need to know what you were seeking here.

**Comment by AV25242** [comment]
Two different things.

An id can be a number however when you search it would need to be a string as all Id's are stored as string. for instance if you dont specify an Id you an Id (GUID) is made available for your. All the methods thereby allows you to find by id which is a string.

**Comment by bwgjoseph** [comment]
I've just tested, and as you said, it seems to support `number` as `id` but it doesn't seem to be stored as `string`, at least not the `meta.id`

![image](https://user-images.githubusercontent.com/37484538/117745421-06b1d900-b23d-11eb-8c24-51725acd9549.png)

Looks like a number to me. If that is intended, then it's fine

**Comment by AV25242** [comment]
Yeah thats right and intended. Id can be anything ranging from number to alphanumeric like I was telling you earlier, if you dont supply the id then its a Guid.
