### ISSUE TITLE
removeById result

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#64]
Hi,

Calling `removeById` method will return `cas` value.

May I know what is the purpose of this return data? Would it be able to return the original data prior to delete?

In `mongoose`, there's a equivalent function called `findOneAndDelete` where it returns the document before deletion

**Comment by AV25242** [comment]
> Calling removeById method will return cas value.
Yeah thats by design to let you know if the most right document was deleted and not a version prior to.

> May I know what is the purpose of this return data? Would it be able to return the original data prior to delete?

At present no, you will have to do a get and then a remove. We can add findOneAndDelete feature in our backlog but that will be for future

**Comment by bwgjoseph** [comment]
Not sure if having https://github.com/couchbaselabs/node-ottoman/issues/463 would also allow `removeById` to return the removed document instead of `cas`?

**Comment by AV25242** [comment]
The alternative to this is to do a findById and then call a RemoveById that way the document thats deleted is available to you before hand.

**Comment by bwgjoseph** [comment]
> The alternative to this is to do a findById and then call a RemoveById that way the document thats deleted is available to you before hand.

Yup, that's exactly what I'm doing it right now. Just not sure if it were be "safe enough" whereby mutation could occur after `findById` and before `removeById` happens

**Comment by AV25242** [comment]
findoneandremove ticket has been created, most likely to be available in the next release

**Comment by AV25242** [comment]
We released [Ottoman beta.9](https://www.npmjs.com/package/ottoman/v/2.0.0-beta.9) today please verify
