### ISSUE TITLE
model options type declaration 

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#65]
Hi,

The `model` type declaration in `ottoman.d.ts` for `options` is missing the types `ModelOptions`

The current one is

```js
export declare const model: (name: string, schema: Schema | Record<string, unknown>, options?: any) => ModelTypes;
```

If you see in the source here - 
https://github.com/couchbaselabs/node-ottoman/blob/cfea7fc59ccf872d51a860f8822a686b820158aa/src/ottoman/ottoman.ts#L222

It is declared correctly, but not in the `ottoman.d.ts` file which is declared as `any`

**Comment by AV25242** [comment]
Our team is looking into it

**Comment by bwgjoseph** [comment]
![image](https://user-images.githubusercontent.com/37484538/117384085-bbce5380-af14-11eb-9750-935a3361666a.png)

**Comment by AV25242** [comment]
Will be made available with next release.

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29
