### ISSUE TITLE
bump jsonpath deps

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#67]
Hi,

According to snyk, there's low vulnerabilities affecting the package. See https://snyk.io/test/npm/ottoman/2.0.0-alpha.22

Upgrading `jsonpath` should resolve it

Thanks

**Comment by AV25242** [comment]
will be ready next release, we need to test the jsonpath version 1.1.1 to ensure everything works. We can also add ottoman package to snyk and show a badge for vulnerabilities and allow snyk to notify us automatically about any new vulnerability detected.

**Comment by AV25242** [comment]
https://github.com/couchbaselabs/node-ottoman/issues/474

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29
