### ISSUE TITLE
Support for returning docs as result in *Many ops

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#68]
Hi,

Is it possible to return the docs that were created/updated/removed in the *Many operations instead of the `ManyQueryResponse` when a param is passed in such as (for example) `new: true` or `raw: true`?

```js
const data = [{ name: 'data1' }, { name: 'data2' }];
const results = model.createMany(data, { raw: true });

// results
[
  {
    id: '12345',
    name: 'data1'
  },
  {
    id: '23456',
    name: 'data2'
  }
]
```

or alternatively, appending the raw result from the creations onto `ManyQueryResponse` like

```js
status: 'SUCCESS',
message: {
    success: 2,
    match_number: 2,
    errors: [],
},
data: [
    {
        id: '12345',
        name: 'data1'
    },
    {
        id: '23456',
        name: 'data2'
    }
]
```

**Comment by AV25242** [comment]
@bwgjoseph  will need to discuss it more will shelve it for future

**Comment by httpJunkie** [comment]
same for removeMany()

**Comment by bwgjoseph** [comment]
To further iterate on this issue with the assumption of the database already having 100 documents,

- if I were to perform a `createMany` with 10 docs, I have no idea which are the 10 documents created now that there are 110 documents
- if I were to perform a `updateMany` with the filter, it could update 50 documents but I have no idea which 50 documents are those that has been updated
- If I were to perform a `removeMany` with the filter, it could remove 40 documents but I have no idea which 40 documents are removed

The `removeMany` is slightly different from the `removeById` case where I do know which `id` I passed into the API for deletion. In `removeMany` case, I do not know what are removed

**Comment by AV25242** [comment]
The issues are created to investigate viable options and see if this is feasible.

**Comment by AV25242** [comment]
I thought this is available to you know please review and let me know.

**Comment by bwgjoseph** [comment]
Sorry, might have missed this. Will take a look later

**Comment by bwgjoseph** [comment]
Have verified it
