### ISSUE TITLE
wait for ottoman to connect

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#7]
For the `ottoman.connect`, is my only option to wait for the connection to be ready is to run `await ottoman.ensureIndexes()`? I don't seem to be able to run `await ottoman.connect` since it just returns a `ConnectionManager`. Is it `ottoman.start`?

**Comment by bwgjoseph** [comment]
@AV25242 replied

We will get back to you on this.

**Comment by bwgjoseph** [comment]
After reading through some docs, and codes, I think `start` should be the correct API to use (do verify), but still have some query.

In the documentation in [v2-schema-indexes](https://v2.ottomanjs.com/guides/schema.html#indexes), the example stated this

```js
const useCollections = false; // set this to true to create scopes/collections.
start({ useCollections })
  .then(() => {
    console.log('Ottoman is ready!');
    app.listen(5000);
  })
```

And the source code for it is at https://github.com/couchbaselabs/node-ottoman/blob/7a2fc9747f4b9532d348072f6974e3c0416c33d7/src/connections/connection-manager.ts#L145-L147

I also do see that in the test cases, it has this method `startInTest` - https://github.com/couchbaselabs/node-ottoman/blob/7a2fc9747f4b9532d348072f6974e3c0416c33d7/__test__/testData.ts#L14 which does a delay. Any specific reason for that?

**Comment by AV25242** [comment]
@bwgjoseph  Start is the method to get bootstrapped.  At present you pass in useCollections, in a future version we would see if this can be auto inferred.

I will get back to you on the startInTest using a delay.

**Comment by bwgjoseph** [comment]
Yup, having the bootstrapped `start` method is really good. 

> I will get back to you on the startInTest using a delay.

Sure, thanks!

**Comment by AV25242** [comment]
@bwgjoseph I have verified from the team, its not a delay for connection, but the delay was to ensure collections and scope are created. Like discussed before that should be handled when we  work on auto-inferring scopes and collections. 

**Answering to your question, there is no need to add a delay while establishing connection** hope this helps !

**Comment by bwgjoseph** [comment]
Thanks for the clarification. I understand that it is a additional wrapper on top of start in test only.

So my question is should I also be doing the same in my test as well?

**Comment by AV25242** [comment]
> Thanks for the clarification. I understand that it is a additional wrapper on top of start in test only.
> 
> So my question is should I also be doing the same in my test as well?

If in your test you expect the collections and scopes to be auto-created  then I would say yes. but if your setup already has scopes and collections then no

**Comment by bwgjoseph** [comment]
By auto-created, you meant the auto creation of `_defaultScope` and _`defaultCollection`?

**Comment by AV25242** [comment]
default scope and collections will be available when you create your bucket. Its named scopes and collections I am talking about

**Comment by bwgjoseph** [comment]
As discussed, ottoman will create behind the scene if not pre-created. Will close this issue for now

**Comment by AV25242** [comment]
@bwgjoseph  I think this issue is still open ?

**Comment by AV25242** [comment]
@bwgjoseph  can you please close this issue ?
