### ISSUE TITLE
Discrepancy in ModelTypes and IModel types

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#70]
Hi,

In `model.types.d.ts`, it has 

```js
export declare type ModelTypes<T = any> = WhateverTypes & IModel<T>;
```

But in `model.d.ts`, it has

```js
export declare class Model<T = any, R = any> extends Document<T>

export interface IModel<T = any, R = any>
```

So `IModel` takes in `T, R` but `ModelTypes` takes in `T` and only passes `T` to `IModel`

Not sure if this is the intended

> alpha.28

**Comment by AV25242** [comment]
https://github.com/couchbaselabs/node-ottoman/issues/471 created

**Comment by AV25242** [comment]
Investigation done. This will be fixed with the next release

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29
