### ISSUE TITLE
return type of model and getModel

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#74]
Hi,

The return type of `model` and `getModel` is slightly different

```js
export declare const getModel: (name: string) => Model<any, any> & (new (data: any, options?: CastOptions | undefined) => any);

export declare const model: <T = any>(name: string, schema: Schema | Record<string, unknown>, options?: any) => import("..").ModelTypes<T>;
```

Should it be the same? returning `ModelTypes`?
The definition also seems slightly different, I'm not quite sure though

I face issue while trying to get back the type

```js
// can be any or ModelTypes
const postModel = getModel(modelName) || model(modelName, schema, modelOptions);

export default postModel;
```

**Comment by AV25242** [comment]
Created an Investigation ticket https://github.com/couchbaselabs/node-ottoman/issues/467

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29
