### ISSUE TITLE
standardize searchConsistency field name

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#77]
Hi,

In [FindOptions](https://v2.ottomanjs.com/classes/findoptions.html#class-findoptions), the fieldname is currently defined as `consistency` but in [OttomanConfig](https://v2.ottomanjs.com/interfaces/ottomanconfig.html#interface-ottomanconfig), it is defined as `searchConsistency`.

I was wondering why it wouldn't work when I was using `searchConsistency` and placing it in the `findOptions` when using `find` API. After hours, then I saw that the naming is not the same.

Note: when using `cluster` query, it is called `scanConsistency`

```js
await getDefaultInstance().cluster.query(query, { scanConsistency: 'request_plus' });
```

Thanks

**Comment by AV25242** [comment]
Thanks names should be consistent 

https://github.com/couchbaselabs/node-ottoman/issues/464 created

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29

**Comment by bwgjoseph** [comment]
`OttomanConfig` has changed to `consistency` but I am unable to verify if `query` has changed

**Comment by httpJunkie** [comment]
The word `scanConsistency` is now  'consistency` across `find()` and `updateMany()` and `OttomanConfig`

**Comment by bwgjoseph** [comment]
Since `scanConsistency` is the node-sdk fieldname, will keep it as is
