### ISSUE TITLE
count usage

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#79]
Hi,

How are the `count` options used? Is there any sample I can look at? I don't find the usage of `count` in the documentation as well

The `count` API is declared as such

```js
export declare type CountOptions = {
    sort?: Record<string, SortType>;
    limit?: number;
    skip?: number;
};

count(filter?: LogicalWhereExpr<T>, options?: CountOptions): Promise<any>;
```

But I'm not sure when would the `options` be used, and in what scenario would it be useful?

Thanks

**Comment by AV25242** [comment]
hello @bwgjoseph  tests are the best place to look. 
https://github.com/couchbaselabs/node-ottoman/blob/master/__test__/model-crud.spec.ts
has quite a few examples

**Comment by AV25242** [comment]
This was an oversight, countoptions will be removed in the next release.
