### ISSUE TITLE
find not returning result

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#8]
You will find that in `ottoman-create.test.js` Line 42, it print the data using `Airline.find()`, but it will not print out any data even though the data has been created, and verified in the UI. However, if I were to run the same test again, and now, the log will shows that there is one result (where it have been two, and ui does have two data). Why does it seem like it is lagging behind one operation? Am I not using the API correctly? Did I missed out anything?

```
// first run, should have 1 row but none
{
  meta: {
    requestId: '6a9acb60-e66c-4e9a-b8ba-effe1974744e',
    clientContextId: 'e053649c8a595c58',
    status: 'success',
    signature: { '*': '*', _type: 'json' },
    profile: undefined,
    metrics: {
      elapsedTime: 2.0655,
      executionTime: 1.9989,
      sortCount: undefined,
      resultCount: 0,
      resultSize: 0,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: []
}

// second run, should have 2 row but only 1
{
  meta: {
    requestId: 'a0e45af2-48c7-4fad-a2a0-d27b81a34a67',
    clientContextId: '77bb3bbb8ab1701f',
    status: 'success',
    signature: { '*': '*', _type: 'json' },
    profile: undefined,
    metrics: {
      elapsedTime: 6.9238,
      executionTime: 6.872,
      sortCount: undefined,
      resultCount: 1,
      resultSize: 160,
      mutationCount: undefined,
      errorCount: undefined,
      warningCount: undefined
    }
  },
  rows: [
    _Model {
      _scope: '_default',
      _type: 'Airline',
      callsign: 'Couchbase',
      country: 'United States',
      id: '6dc26494-1ff7-4e65-99a6-666456ab7980',
      name: 'Couchbase Airlines'
    }
  ]
}
```

**Comment by bwgjoseph** [comment]
@AV25242 replied

You will have to specify  the Consistency as a  `Find Option`  find uses n1ql behind the scenes and the index consistency defines the accuracy of data you need. By default its none, specifying and passin in the consistency will give you the data you created.

`const options = { consistency: ottoman.SearchConsistency.LOCAL }`

**Comment by bwgjoseph** [comment]
I have tested this, and verified that this is working.

Is there any way I can reference the docs on what exactly is `SearchConsistency`. I have read the [searchconsistency](https://v2.ottomanjs.com/enums/searchconsistency.html) but still don't get quite get it.

**Comment by AV25242** [comment]
Probably you might want to know more about Consistency in general  [Read Index Consistency](https://docs.couchbase.com/server/current/learn/services-and-indexes/indexes/index-replication.html#index-consistency)

**Comment by bwgjoseph** [comment]
Thanks! I think this is what I'm looking for. 

Can I assume that 

```
NONE = not_bounded
LOCAL = at_plus
GLOBAL = request_plus
```

**Comment by AV25242** [comment]
That is correct Joseph !

**Comment by bwgjoseph** [comment]
Great, I will read up more on this. 

Thank you! Will close this issue now.
