### ISSUE TITLE
2.0.0-beta.1  released

### ISSUE THREAD

**Issue by AV25242** [bwgjoseph/mongoose-vs-ottoman#84]
@bwgjoseph and team we are happy to announce the release of the first [Beta for Ottoman](https://www.npmjs.com/package/ottoman/v/2.0.0-beta.1).

The documentation can currently be found  at v2.ottomanjs.com. 

Beta of Ottoman is build on top of Node.js SDK 3.1.1. 

Please let us know your feedback.

**Comment by bwgjoseph** [comment]
Congrats on the milestone, @AV25242 and team

Question: why revert back to Couchbase 3.1.1 from 3.1.2 though?

**Comment by AV25242** [comment]
Thanks @bwgjoseph , yeah we went back on purpose.

3.1.1 is compatible with the 7.0 Beta that you can download

the versions above that are the ones compatible with 7.0 versions that are internal and not yet public (release candidates)

**Comment by bwgjoseph** [comment]
I see, thanks!
