### ISSUE TITLE
support for query params for all operations

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#85]
Hi,

Currently, querying using `id and query` is not supported. In short, when using `*byId` method, it only take in account the `id` and not the additional options provided.

```js
// this is not supported now
.findById('12345', { name: 'hello' });
// the above basically means AND
// so it translate to
// find all doc that matches { name: 'hello', id: '12345' }
.find({ name: 'hello', id: '12345' })
``` 

Similarly, for all other `byId` methods

```js
// this is not supported now
.updateById('12345', { name: 'hello' }, { isBulk: true });
// the above basically means AND
// so it translate to
// all docs that matches { isBulk: true, id: '12345' } should update name to 'hello'
.updateMany({ isBulk: true, id: '12345' }, { name: 'hello' })
``` 

P.S: As for all operations, to be more specific, it should be the following

```js
findById
updateById
replaceById
removeById
```

I hope I did not miss out any

**Comment by AV25242** [comment]
@bwgjoseph I dont see how beneficial this feature is. for instance findById as the name suggest is used to find documents by Id  and for extended needs you always have the find method. its more confusing than complementing.

**Comment by AV25242** [comment]
Yeah this will be very confusing if we allow selection by other fields in a ById function.

**Comment by bwgjoseph** [comment]
I think that's fine at the moment. Will revisit again if I have any strong use-case to support it
