### ISSUE TITLE
simplify operator usage

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#87]
Hi,

I was wondering if `$in` (and maybe some other operator) could further simplify the usage?

```js
// from 
.find({
    $in: {
        search_expr: 'model',
        target_expr: ['767-300F']
        }
}

// to
.find({
	model : {
		$in : ['767-300F']
	}
}
```

It definitely helps in DX as I would think that `search_expr` and `target_expr` are not helping much here and could be abstracted away.

I wasn't quite sure of how the other operators (especially `COLLECTION`) is used exactly, so not sure if those have special syntax like `$in` and can be abstracted away

Thanks

**Comment by bwgjoseph** [comment]
Here's another one

```js
// instead of
{
    $not: [{
        $in : {
            search_expr: 'model',
            target_expr: ['767-300F'],
        }
    }]
}

// maybe
.find({
	model : {
		$nin: ['767-300F']
                // or
		$notIn: ['767-300F']
	}
}
```

which is in line with the previous `$in` suggestion

Will continue to list on as I discover more

**Comment by AV25242** [comment]
so yeah the strong reason for doing it in a way it is today is more aligned with backward compatibility. If this is changed customers on 1.0 will have breaking changes.

**Comment by bwgjoseph** [comment]
I thought that there are already breaking changes in the API from v1 to v2, so this is actually a good chance to catch the train and make the changes altogether.

**Comment by AV25242** [comment]
Check the most reason $in [v2.0.0-beta.3 released]( https://www.npmjs.com/package/ottoman/v/2.0.0-beta.3)
