### ISSUE TITLE
schemaOptions - timestamp

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#89]
Hi,

I totally overlooked this out, but could you support this [timestamp option](https://mongoosejs.com/docs/guide.html#timestamps)

In short, by specifying the `timestamp` option, it will auto-create `createdAt` and `updatedAt` field (default) and maintain the timestamp whenever doc create/update. It also have the option to override and specific the field as a different name than `createdAt` and `updatedAt`.

This is a [article](https://masteringjs.io/tutorials/mongoose/timestamps) too, if I'm not being clear

Thank you!

**Comment by AV25242** [comment]
We added this to our next release. You should be able to see this in

**Comment by AV25242** [comment]
Available with beta 4 please review
