### ISSUE TITLE
ottoman not exported in type definition

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#9]
It seem like `ottoman` is not being exported?

When I do (in typescript)

```js
import ottoman from 'ottoman';

// throws ottoman is undefined error
ottoman.Schema

// I have to
import { Schema } from 'ottoman'
```

Is this on purpose? Can it be exported?

**Comment by AV25242** [comment]
Looks like it can be exported 

the correct statement for this case is:
 ` import * as ottoman from 'ottoman'; `

**Comment by bwgjoseph** [comment]
My project has `esModuleInterop` set to true but `import ottoman from 'ottoman'` doesn't work. I tried to print out `ottoman` and it is `undefined`

`import * as ottoman from 'ottoman'` works though

**Comment by AV25242** [comment]
> My project has `esModuleInterop` set to true but `import ottoman from 'ottoman'` doesn't work. I tried to print out `ottoman` and it is `undefined`
> 
> `import * as ottoman from 'ottoman'` works though

Thanks for the update, I will let the team know. Meanwhile continue to use import * syntax

**Comment by AV25242** [comment]
@bwgjoseph  this can be closed as there is a workaround and also an issue https://github.com/couchbaselabs/node-ottoman/issues/320 is created to address the `import ottoman from ottoman `issue
