### ISSUE TITLE
what is the behavior of passing negative limit?

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#91]
Hi,

May I know what is the behavior of passing negative limit in `ottoman/couchbase`? Is there any doc for this?

[This is how](https://docs.mongodb.com/manual/reference/method/cursor.limit/#negative-values) MongoDB handles it

I did a quick test, and it seems that it is being ignored? and return no results

Thanks

**Comment by bwgjoseph** [comment]
Hmm, did you assigned it back to me accidentally?

**Comment by AV25242** [comment]
Ha! good catch that should be the case, sorry about that

**Comment by bwgjoseph** [comment]
Great, thanks!
