### ISSUE TITLE
feathers-ottoman v0.1.0 released

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#92]
With the release of `ottoman-2.0.0-beta.1`, I also recently released [feathers-ottoman](https://github.com/bwgjoseph/feathers-ottoman) as the database adapter for us to use with [feathersjs](https://feathersjs.com/).

Thank you for the continuous support on `ottoman`

**Comment by AV25242** [comment]
wohoo ! awesome folks, congrats.
