### ISSUE TITLE
$isNull operator

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#95]
Hi,

I was testing out `$isNull` operator but found out that there's either issue with `null` value, or I am not using it correctly.

```js
const schema = new Schema({
  text: { type: String },
  review: { type: String }
});

ottoman.model('message', schema, modelOptions);

const messageModel = getModel('message');

messageModel.create({ text: null, review: 'test' })
messageModel.create({ text: 'hello', review: 'test' })

messageModel.find({ text: { $isNull: true } });
```

However, if you create with `null` as the `value`, it get stores as a `string` in database and even if I change the `value` in database manually to `null` (not a string null), when I use `ottoman` to pull the data, it will be converted to `string null`

Something like this

[I changed the value to non-string null manually]
![image](https://user-images.githubusercontent.com/37484538/121802659-0cea0980-cc70-11eb-86ec-68a3da0578df.png)

[The data from .find still gives string null]
![image](https://user-images.githubusercontent.com/37484538/121802669-21c69d00-cc70-11eb-8a8f-708cfe674610.png)

Hence, there is no way to create a `null` value and `$isNull` operator cannot be used if I'm right so far

Thanks!

**Comment by AV25242** [comment]
Thanks @bwgjoseph will get back to the team for investigation.

**Comment by AV25242** [comment]
Will be fixed with next Beta release.

**Comment by AV25242** [comment]
Beta 2.0 is released and should have fixed this issue.
